// ===========================================================
// HLS sources generated by ActiveCore framework
// Date: 2022-01-02 17:07:58
// Copyright Alexander Antonov <antonov.alex.alex@gmail.com>
// ===========================================================

#include <ap_int.h>
#include <hls_stream.h>
#include "riscv_2stage.hpp"

typedef struct {
	ap_uint<1> if_id;
	ap_uint<1> resp_done;
	ap_uint<32> rdata;
	ap_uint<1> rdreq_pending;
	ap_uint<1> tid;
} genmcopipe_handle_instr_mem_struct;

typedef struct {
	ap_uint<1> instr_req_done;
	genmcopipe_handle_instr_mem_struct genmcopipe_handle_instr_mem;
} genpstage_IFETCH_TRX_BUF_STRUCT;

typedef struct {
	ap_uint<1> if_id;
	ap_uint<1> resp_done;
	ap_uint<32> rdata;
	ap_uint<1> rdreq_pending;
	ap_uint<2> tid;
} genmcopipe_handle_coproc_M_if_struct;

typedef struct {
	ap_uint<1> if_id;
	ap_uint<1> resp_done;
	ap_uint<32> rdata;
	ap_uint<1> rdreq_pending;
	ap_uint<1> tid;
} genmcopipe_handle_data_mem_struct;

typedef struct {
	ap_uint<32> curinstr_addr;
	ap_uint<32> nextinstr_addr;
	ap_uint<1> irq_recv;
	ap_uint<8> irq_mcause;
	ap_uint<1> Ext_coproc_req_done;
	ap_uint<1> jump_req_done;
	ap_uint<1> data_req_done;
	genmcopipe_handle_coproc_M_if_struct genmcopipe_handle_coproc_M_if;
	genmcopipe_handle_data_mem_struct genmcopipe_handle_data_mem;
	genmcopipe_handle_instr_mem_struct genmcopipe_handle_instr_mem;
} genpstage_EXEC_TRX_BUF_STRUCT;

typedef struct {
	ap_uint<32> curinstr_addr;
	ap_uint<32> nextinstr_addr;
	ap_uint<1> instr_req_done;
	riscv_2stage_busreq_mem_struct instr_busreq;
} genpstage_IFETCH_TRX_LOCAL_STRUCT;

typedef struct {
	ap_uint<32> instr_code;
	ap_uint<7> opcode;
	ap_uint<1> alu_unsigned;
	ap_uint<5> rs1_addr;
	ap_uint<5> rs2_addr;
	ap_uint<5> rd_addr;
	ap_uint<3> funct3;
	ap_uint<7> funct7;
	ap_uint<5> shamt;
	ap_uint<4> pred;
	ap_uint<4> succ;
	ap_uint<12> csrnum;
	ap_uint<5> zimm;
	ap_uint<32> immediate_I;
	ap_uint<32> immediate_S;
	ap_uint<32> immediate_B;
	ap_uint<32> immediate_U;
	ap_uint<32> immediate_J;
	ap_uint<2> op1_source;
	ap_uint<1> rd_req;
	ap_uint<3> rd_source;
	ap_uint<32> immediate;
	ap_uint<2> op2_source;
	ap_uint<1> alu_req;
	ap_uint<4> alu_opcode;
	ap_uint<1> jump_req;
	ap_uint<1> jump_src;
	ap_uint<1> rs1_req;
	ap_uint<1> rs2_req;
	ap_uint<1> jump_req_cond;
	ap_uint<1> mem_req;
	ap_uint<1> mem_cmd;
	ap_uint<1> ext_coproc_req;
	ap_uint<1> m_ext_req;
	ap_uint<1> fencereq;
	ap_uint<1> ebreakreq;
	ap_uint<1> ecallreq;
	ap_uint<1> csrreq;
	ap_uint<1> custom0_ext_req;
	ap_uint<4> mem_be;
	ap_uint<1> load_signext;
	ap_uint<1> mret_req;
	ap_uint<32> rs1_rdata;
	ap_uint<32> rs2_rdata;
	ap_uint<32> csr_rdata;
	ap_uint<32> alu_op1;
	ap_uint<32> alu_op2;
	ap_uint<33> alu_op1_wide;
	ap_uint<33> alu_op2_wide;
	ap_uint<8> irq_mcause;
	ap_uint<1> irq_recv;
	riscv_2stage_Ext_coproc_struct Ext_coproc_busreq;
	ap_uint<1> Ext_coproc_req_done;
	ap_uint<33> alu_result_wide;
	ap_uint<32> alu_result;
	ap_uint<1> alu_CF;
	ap_uint<1> alu_SF;
	ap_uint<1> alu_ZF;
	ap_uint<1> alu_OF;
	ap_uint<1> alu_overflow;
	ap_uint<32> rd_wdata;
	ap_uint<1> rd_rdy;
	ap_uint<32> curinstraddr_imm;
	ap_uint<32> jump_vector;
	ap_uint<32> mem_addr;
	ap_uint<32> mem_wdata;
	ap_uint<1> jump_req_done;
	riscv_2stage_busreq_mem_struct data_busreq;
	ap_uint<1> data_req_done;
	ap_uint<32> mem_rdata;
	ap_uint<32> curinstr_addr;
	ap_uint<32> nextinstr_addr;
} genpstage_EXEC_TRX_LOCAL_STRUCT;

ap_uint<32> genpsticky_glbl_pc;
ap_uint<32> genpsticky_glbl_regfile [32];
ap_uint<1> genpsticky_glbl_jump_req_cmd;
ap_uint<32> genpsticky_glbl_jump_vector_cmd;
ap_uint<8> genpsticky_glbl_CSR_MCAUSE;
ap_uint<1> genpsticky_glbl_MIRQEN;
ap_uint<32> genpsticky_glbl_MRETADDR;
ap_uint<1> genmcopipe_instr_mem_wr_done;
ap_uint<1> genmcopipe_instr_mem_rd_done;
ap_uint<1> genmcopipe_instr_mem_full_flag;
ap_uint<1> genmcopipe_instr_mem_empty_flag;
ap_uint<1> genmcopipe_instr_mem_wr_ptr;
ap_uint<1> genmcopipe_instr_mem_rd_ptr;
ap_uint<1> genmcopipe_data_mem_wr_done;
ap_uint<1> genmcopipe_data_mem_rd_done;
ap_uint<1> genmcopipe_data_mem_full_flag;
ap_uint<1> genmcopipe_data_mem_empty_flag;
ap_uint<1> genmcopipe_data_mem_wr_ptr;
ap_uint<1> genmcopipe_data_mem_rd_ptr;
ap_uint<1> genmcopipe_coproc_M_if_wr_done;
ap_uint<1> genmcopipe_coproc_M_if_rd_done;
ap_uint<1> genmcopipe_coproc_M_if_full_flag;
ap_uint<1> genmcopipe_coproc_M_if_empty_flag;
ap_uint<2> genmcopipe_coproc_M_if_wr_ptr;
ap_uint<2> genmcopipe_coproc_M_if_rd_ptr;
ap_uint<1> genmcopipe_coproc_custom0_if_wr_done;
ap_uint<1> genmcopipe_coproc_custom0_if_rd_done;
ap_uint<1> genmcopipe_coproc_custom0_if_full_flag;
ap_uint<1> genmcopipe_coproc_custom0_if_empty_flag;
ap_uint<2> genmcopipe_coproc_custom0_if_wr_ptr;
ap_uint<2> genmcopipe_coproc_custom0_if_rd_ptr;
genpstage_IFETCH_TRX_BUF_STRUCT genpstage_IFETCH_TRX_BUF [0:0];
ap_uint<1> genpstage_IFETCH_TRX_BUF_COUNTER;
ap_uint<1> genpstage_IFETCH_TRX_BUF_COUNTER_NEMPTY;
ap_uint<1> genpstage_IFETCH_TRX_BUF_COUNTER_FULL;
ap_uint<1> genpstage_IFETCH_genctrl_stalled_glbl;
genpstage_EXEC_TRX_BUF_STRUCT genpstage_EXEC_TRX_BUF [0:0];
ap_uint<1> genpstage_EXEC_TRX_BUF_COUNTER;
ap_uint<1> genpstage_EXEC_TRX_BUF_COUNTER_NEMPTY;
ap_uint<1> genpstage_EXEC_TRX_BUF_COUNTER_FULL;
ap_uint<1> genpstage_EXEC_genctrl_stalled_glbl;

void riscv_2stage(ap_uint<1> geninit, hls::stream<ap_uint<8> >& irq_fifo, hls::stream<ap_uint<32> >& genmcopipe_instr_mem_resp, hls::stream<ap_uint<32> >& genmcopipe_data_mem_resp, hls::stream<ap_uint<32> >& genmcopipe_coproc_M_if_resp, hls::stream<ap_uint<32> >& genmcopipe_coproc_custom0_if_resp, hls::stream<genpmodule_riscv_2stage_genmcopipe_instr_mem_genstruct_fifo_wdata>& genmcopipe_instr_mem_req, hls::stream<genpmodule_riscv_2stage_genmcopipe_data_mem_genstruct_fifo_wdata>& genmcopipe_data_mem_req, hls::stream<genpmodule_riscv_2stage_genmcopipe_coproc_M_if_genstruct_fifo_wdata>& genmcopipe_coproc_M_if_req, hls::stream<genpmodule_riscv_2stage_genmcopipe_coproc_custom0_if_genstruct_fifo_wdata>& genmcopipe_coproc_custom0_if_req) {


	ap_uint<1> genmcopipe_instr_mem_wr_ptr_next;
	ap_uint<1> genmcopipe_instr_mem_rd_ptr_next;
	ap_uint<1> genmcopipe_data_mem_wr_ptr_next;
	ap_uint<1> genmcopipe_data_mem_rd_ptr_next;
	ap_uint<2> genmcopipe_coproc_M_if_wr_ptr_next;
	ap_uint<2> genmcopipe_coproc_M_if_rd_ptr_next;
	ap_uint<2> genmcopipe_coproc_custom0_if_wr_ptr_next;
	ap_uint<2> genmcopipe_coproc_custom0_if_rd_ptr_next;
	ap_uint<1> genpstage_IFETCH_genpctrl_flushreq;
	genpstage_IFETCH_TRX_LOCAL_STRUCT genpstage_IFETCH_TRX_LOCAL;
	genpstage_IFETCH_TRX_BUF_STRUCT genpstage_IFETCH_TRX_PUSHED;
	ap_uint<1> genpstage_IFETCH_genctrl_active;
	ap_uint<1> genpstage_IFETCH_genctrl_working;
	ap_uint<1> genpstage_IFETCH_genctrl_succ;
	ap_uint<1> genpstage_IFETCH_genctrl_occupied;
	ap_uint<1> genpstage_IFETCH_genctrl_rdy;
	ap_uint<1> genpstage_IFETCH_genctrl_new;
	ap_uint<1> genpstage_IFETCH_genctrl_finish;
	ap_uint<1> gen155_pipex_succreq;
	ap_uint<32> gen156_pipex_succbuf;
	ap_uint<1> genpstage_EXEC_genpctrl_flushreq;
	genpstage_EXEC_TRX_LOCAL_STRUCT genpstage_EXEC_TRX_LOCAL;
	genpstage_EXEC_TRX_BUF_STRUCT genpstage_EXEC_TRX_PUSHED;
	ap_uint<1> genpstage_EXEC_genctrl_active;
	ap_uint<1> genpstage_EXEC_genctrl_working;
	ap_uint<1> genpstage_EXEC_genctrl_succ;
	ap_uint<1> genpstage_EXEC_genctrl_occupied;
	ap_uint<1> genpstage_EXEC_genctrl_rdy;
	ap_uint<1> genpstage_EXEC_genctrl_new;
	ap_uint<1> genpstage_EXEC_genctrl_finish;
	ap_uint<1> gen157_pipex_var;
	ap_uint<33> gen158_pipex_var;
	ap_uint<1> gen159_pipex_var;
	ap_uint<1> gen160_pipex_var;
	ap_uint<1> gen161_pipex_var;
	ap_uint<1> gen162_pipex_var;
	ap_uint<1> gen163_pipex_var;
	ap_uint<1> gen164_pipex_var;
	ap_uint<1> gen165_pipex_var;
	ap_uint<1> gen166_pipex_var;
	ap_uint<1> gen167_pipex_var;
	ap_uint<32> gen168_pipex_var;
	ap_uint<1> gen169_pipex_var;
	ap_uint<32> gen170_pipex_var;
	ap_uint<12> gen171_pipex_var;
	ap_uint<1> gen172_pipex_var;
	ap_uint<32> gen173_pipex_var;
	ap_uint<13> gen174_pipex_var;
	ap_uint<1> gen175_pipex_var;
	ap_uint<32> gen176_pipex_var;
	ap_uint<32> gen177_pipex_var;
	ap_uint<21> gen178_pipex_var;
	ap_uint<1> gen179_pipex_var;
	ap_uint<32> gen180_pipex_var;
	ap_uint<1> gen181_pipex_var;
	ap_uint<1> gen182_pipex_var;
	ap_uint<1> gen183_pipex_var;
	ap_uint<1> gen184_pipex_var;
	ap_uint<32> gen185_pipex_var;
	ap_uint<1> gen186_pipex_var;
	ap_uint<1> gen187_pipex_var;
	ap_uint<32> gen188_pipex_var;
	ap_uint<1> gen189_pipex_var;
	ap_uint<1> gen190_pipex_var;
	ap_uint<1> gen191_pipex_var;
	ap_uint<1> gen192_pipex_var;
	ap_uint<1> gen193_pipex_var;
	ap_uint<1> gen194_pipex_var;
	ap_uint<1> gen195_pipex_var;
	ap_uint<1> gen196_pipex_var;
	ap_uint<32> gen197_pipex_var;
	ap_uint<32> gen198_pipex_var;
	ap_uint<32> gen199_pipex_var;
	ap_uint<1> gen200_pipex_var;
	ap_uint<1> gen201_pipex_var;
	ap_uint<1> gen202_pipex_var;
	ap_uint<1> gen203_pipex_var;
	ap_uint<1> gen204_pipex_var;
	ap_uint<32> gen205_pipex_var [32];
	ap_uint<32> gen206_pipex_var [32];
	ap_uint<1> gen207_pipex_var;
	ap_uint<1> gen208_pipex_var;
	ap_uint<1> gen209_pipex_var;
	ap_uint<1> gen210_pipex_var;
	ap_uint<1> gen211_pipex_var;
	ap_uint<1> gen212_pipex_var;
	ap_uint<33> gen213_pipex_var;
	ap_uint<33> gen214_pipex_var;
	ap_uint<1> gen215_pipex_var;
	ap_uint<1> gen216_pipex_var;
	ap_uint<33> gen217_pipex_var;
	ap_uint<1> gen218_pipex_var;
	ap_uint<33> gen219_pipex_var;
	ap_uint<1> gen220_pipex_var;
	ap_uint<1> gen221_pipex_var;
	ap_uint<1> gen222_pipex_var;
	ap_uint<1> gen223_pipex_var;
	ap_uint<1> gen224_pipex_var;
	ap_uint<1> gen225_pipex_var;
	ap_uint<1> gen226_pipex_var;
	ap_uint<1> gen227_pipex_var;
	ap_uint<1> gen228_pipex_var;
	ap_uint<1> gen229_pipex_var;
	ap_uint<1> gen230_pipex_var;
	ap_uint<1> gen231_pipex_var;
	ap_uint<1> gen232_pipex_var;
	ap_uint<1> gen233_pipex_var;
	ap_uint<1> gen234_pipex_var;
	ap_uint<1> gen235_pipex_var;
	ap_uint<1> gen236_pipex_var;
	ap_uint<34> gen237_pipex_var;
	ap_uint<34> gen238_pipex_var;
	ap_uint<33> gen239_pipex_var;
	ap_uint<33> gen240_pipex_var;
	ap_uint<33> gen241_pipex_var;
	ap_uint<64> gen242_pipex_var;
	ap_uint<64> gen243_pipex_var;
	ap_uint<32> gen244_pipex_var;
	ap_uint<1> gen245_pipex_var;
	ap_uint<64> gen246_pipex_var;
	ap_uint<64> gen247_pipex_var;
	ap_uint<33> gen248_pipex_var;
	ap_uint<33> gen249_pipex_var;
	ap_uint<33> gen250_pipex_var;
	ap_uint<1> gen251_pipex_var;
	ap_uint<1> gen252_pipex_var;
	ap_uint<1> gen253_pipex_var;
	ap_uint<1> gen254_pipex_var;
	ap_uint<1> gen255_pipex_var;
	ap_uint<1> gen256_pipex_var;
	ap_uint<1> gen257_pipex_var;
	ap_uint<1> gen258_pipex_var;
	ap_uint<1> gen259_pipex_var;
	ap_uint<1> gen260_pipex_var;
	ap_uint<1> gen261_pipex_var;
	ap_uint<1> gen262_pipex_var;
	ap_uint<33> gen263_pipex_var;
	ap_uint<1> gen264_pipex_var;
	ap_uint<1> gen265_pipex_var;
	ap_uint<1> gen266_pipex_var;
	ap_uint<1> gen267_pipex_var;
	ap_uint<1> gen268_pipex_var;
	ap_uint<1> gen269_pipex_var;
	ap_uint<1> gen270_pipex_var;
	ap_uint<1> gen271_pipex_var;
	ap_uint<1> gen272_pipex_var;
	ap_uint<1> gen273_pipex_var;
	ap_uint<1> gen274_pipex_var;
	ap_uint<1> gen275_pipex_var;
	ap_uint<1> gen276_pipex_var;
	ap_uint<1> gen277_pipex_var;
	ap_uint<1> gen278_pipex_var;
	ap_uint<1> gen279_pipex_var;
	ap_uint<1> gen280_pipex_var;
	ap_uint<1> gen281_pipex_var;
	ap_uint<1> gen282_pipex_var;
	ap_uint<1> gen283_pipex_var;
	ap_uint<1> gen284_pipex_var;
	ap_uint<1> gen285_pipex_var;
	ap_uint<1> gen286_pipex_var;
	ap_uint<1> gen287_pipex_var;
	ap_uint<1> gen288_pipex_var;
	ap_uint<1> gen289_pipex_var;
	ap_uint<1> gen290_pipex_var;
	ap_uint<8> gen291_pipex_var;
	ap_uint<1> gen292_pipex_var;
	ap_uint<32> gen293_pipex_var;
	ap_uint<1> gen294_pipex_var;
	ap_uint<32> gen295_pipex_var;
	ap_uint<1> gen296_pipex_var;
	ap_uint<1> gen297_pipex_var;
	ap_uint<1> gen298_pipex_var;
	ap_uint<16> gen299_pipex_var;
	ap_uint<1> gen300_pipex_var;
	ap_uint<32> gen301_pipex_var;
	ap_uint<1> gen302_pipex_var;
	ap_uint<32> gen303_pipex_var;
	ap_uint<1> gen304_pipex_var;
	ap_uint<1> gen305_pipex_var;
	ap_uint<1> gen306_pipex_var;
	ap_uint<1> gen307_pipex_var;
	ap_uint<1> gen308_pipex_var;
	ap_uint<1> gen309_pipex_var;
	ap_uint<1> gen310_pipex_var;
	ap_uint<1> gen311_pipex_var;
	ap_uint<32> gen312_pipex_mcopipe_rdata;
	ap_uint<32> gen313_pipex_mcopipe_rdata;
	ap_uint<32> gen314_pipex_mcopipe_rdata;
	ap_uint<32> gen315_pipex_mcopipe_rdata;
	genpmodule_riscv_2stage_genmcopipe_coproc_M_if_genstruct_fifo_wdata gen316_pipex_req_struct;
	genpmodule_riscv_2stage_genmcopipe_coproc_custom0_if_genstruct_fifo_wdata gen317_pipex_req_struct;
	genpmodule_riscv_2stage_genmcopipe_data_mem_genstruct_fifo_wdata gen318_pipex_req_struct;
	ap_uint<32> gen319_pipex_mcopipe_rdata;
	genpmodule_riscv_2stage_genmcopipe_instr_mem_genstruct_fifo_wdata gen320_pipex_req_struct;
	genpstage_EXEC_TRX_BUF_STRUCT genpstage_EXEC_push_trx;
	ap_uint<1> gen202_cyclix_var;
	ap_uint<1> gen203_cyclix_var;
	ap_uint<1> gen204_cyclix_var;
	ap_uint<1> gen205_cyclix_var;
	ap_uint<1> gen206_cyclix_var;
	ap_uint<1> gen207_cyclix_var;
	ap_uint<1> gen208_cyclix_var;
	ap_uint<1> gen209_cyclix_var;
	ap_uint<1> gen210_cyclix_var;
	ap_uint<1> gen211_cyclix_var;
	ap_uint<1> gen212_cyclix_var;
	ap_uint<1> gen213_cyclix_var;
	ap_uint<1> gen214_cyclix_var;
	ap_uint<1> gen215_cyclix_var;
	ap_uint<1> gen216_cyclix_var;
	ap_uint<1> gen217_cyclix_var;
	ap_uint<1> gen218_cyclix_var;
	ap_uint<1> gen219_cyclix_var;
	ap_uint<1> gen220_cyclix_var;
	ap_uint<1> gen221_cyclix_var;
	ap_uint<1> gen222_cyclix_var;
	ap_uint<1> gen223_cyclix_var;
	ap_uint<1> gen224_cyclix_var;
	ap_uint<1> gen225_cyclix_var;
	ap_uint<1> gen226_cyclix_var;
	ap_uint<1> gen227_cyclix_var;
	ap_uint<1> gen228_cyclix_var;
	ap_uint<1> gen229_cyclix_var;
	ap_uint<1> gen230_cyclix_var;
	ap_uint<1> gen231_cyclix_var;
	ap_uint<1> gen232_cyclix_var;
	ap_uint<1> gen233_cyclix_var;
	ap_uint<1> gen234_cyclix_var;
	ap_uint<1> gen235_cyclix_var;
	ap_uint<1> gen236_cyclix_var;
	ap_uint<1> gen237_cyclix_var;
	ap_uint<1> gen238_cyclix_var;
	ap_uint<1> gen239_cyclix_var;
	ap_uint<1> gen240_cyclix_var;
	ap_uint<1> gen241_cyclix_var;
	ap_uint<1> gen242_cyclix_var;
	ap_uint<1> gen243_cyclix_var;
	ap_uint<1> gen244_cyclix_var;
	ap_uint<1> gen245_cyclix_var;
	ap_uint<1> gen246_cyclix_var;
	ap_uint<1> gen247_cyclix_var;
	ap_uint<1> gen248_cyclix_var;
	ap_uint<1> gen249_cyclix_var;
	ap_uint<32> gen250_cyclix_var [32];
	ap_uint<1> gen251_cyclix_var;
	ap_uint<1> gen252_cyclix_var;
	ap_uint<1> gen253_cyclix_var;
	ap_uint<1> gen254_cyclix_var;
	ap_uint<1> gen255_cyclix_var;
	ap_uint<1> gen256_cyclix_var;
	ap_uint<1> gen257_cyclix_var;
	ap_uint<1> gen258_cyclix_var;
	ap_uint<1> gen259_cyclix_var;
	ap_uint<1> gen260_cyclix_var;
	ap_uint<1> gen261_cyclix_var;
	ap_uint<1> gen262_cyclix_var;
	ap_uint<1> gen263_cyclix_var;
	ap_uint<1> gen264_cyclix_var;
	ap_uint<1> gen265_cyclix_var;
	ap_uint<1> gen266_cyclix_var;
	ap_uint<1> gen267_cyclix_var;
	ap_uint<1> gen268_cyclix_var;
	ap_uint<1> gen269_cyclix_var;
	ap_uint<1> gen270_cyclix_var;
	ap_uint<1> gen271_cyclix_var;
	ap_uint<1> gen272_cyclix_var;
	ap_uint<1> gen273_cyclix_var;
	ap_uint<1> gen274_cyclix_var;
	ap_uint<1> gen275_cyclix_var;
	ap_uint<1> gen276_cyclix_var;
	ap_uint<1> gen277_cyclix_var;
	ap_uint<1> gen278_cyclix_var;
	ap_uint<1> gen279_cyclix_var;
	ap_uint<1> gen280_cyclix_var;
	ap_uint<1> gen281_cyclix_var;
	ap_uint<1> gen282_cyclix_var;
	ap_uint<1> gen283_cyclix_var;
	ap_uint<1> gen284_cyclix_var;
	ap_uint<1> gen285_cyclix_var;
	ap_uint<1> gen286_cyclix_var;
	ap_uint<1> gen287_cyclix_var;
	ap_uint<1> gen288_cyclix_var;
	ap_uint<1> gen289_cyclix_var;
	ap_uint<1> gen290_cyclix_var;
	ap_uint<1> gen291_cyclix_var;
	ap_uint<1> gen292_cyclix_var;
	ap_uint<1> gen293_cyclix_var;
	ap_uint<1> gen294_cyclix_var;
	ap_uint<1> gen295_cyclix_var;
	ap_uint<1> gen296_cyclix_var;
	ap_uint<1> gen297_cyclix_var;
	ap_uint<1> gen298_cyclix_var;
	ap_uint<1> gen299_cyclix_var;
	ap_uint<1> gen300_cyclix_var;
	ap_uint<1> gen301_cyclix_var;
	ap_uint<1> gen302_cyclix_var;
	ap_uint<1> gen303_cyclix_var;
	ap_uint<1> gen304_cyclix_var;
	ap_uint<1> gen305_cyclix_var;
	ap_uint<1> gen306_cyclix_var;
	ap_uint<1> gen307_cyclix_var;
	ap_uint<1> gen308_cyclix_var;
	ap_uint<1> gen309_cyclix_var;
	ap_uint<1> gen310_cyclix_var;
	ap_uint<1> gen311_cyclix_var;
	ap_uint<1> gen312_cyclix_var;
	ap_uint<1> gen313_cyclix_var;
	ap_uint<1> gen314_cyclix_var;
	ap_uint<1> gen315_cyclix_var;
	ap_uint<1> gen316_cyclix_var;
	ap_uint<1> gen317_cyclix_var;
	ap_uint<1> gen318_cyclix_var;
	ap_uint<1> gen319_cyclix_var;
	ap_uint<1> gen320_cyclix_var;
	ap_uint<1> gen321_cyclix_var;
	ap_uint<1> gen322_cyclix_var;
	ap_uint<1> gen323_cyclix_var;
	ap_uint<1> gen324_cyclix_var;
	ap_uint<1> gen325_cyclix_var;
	ap_uint<1> gen326_cyclix_var;
	ap_uint<1> gen327_cyclix_var;
	ap_uint<1> gen328_cyclix_var;
	ap_uint<1> gen329_cyclix_var;
	ap_uint<1> gen330_cyclix_var;
	ap_uint<1> gen331_cyclix_var;
	ap_uint<1> gen332_cyclix_var;
	ap_uint<1> gen333_cyclix_var;
	ap_uint<1> gen334_cyclix_var;
	ap_uint<1> gen335_cyclix_var;
	ap_uint<1> gen336_cyclix_var;
	ap_uint<1> gen337_cyclix_var;
	ap_uint<1> gen338_cyclix_var;
	ap_uint<1> gen339_cyclix_var;
	ap_uint<1> gen340_cyclix_var;
	ap_uint<1> gen341_cyclix_var;
	ap_uint<1> gen342_cyclix_var;
	ap_uint<1> gen343_cyclix_var;
	ap_uint<1> gen344_cyclix_var;
	ap_uint<1> gen345_cyclix_var;
	ap_uint<1> gen346_cyclix_var;
	ap_uint<1> gen347_cyclix_var;
	ap_uint<1> gen348_cyclix_var;
	ap_uint<1> gen349_cyclix_var;
	ap_uint<1> gen350_cyclix_var;
	ap_uint<1> gen351_cyclix_var;
	ap_uint<1> gen352_cyclix_var;
	ap_uint<1> gen353_cyclix_var;
	ap_uint<1> gen354_cyclix_var;
	ap_uint<1> gen355_cyclix_var;
	ap_uint<1> gen356_cyclix_var;
	ap_uint<1> gen357_cyclix_var;
	ap_uint<1> gen358_cyclix_var;
	ap_uint<1> gen359_cyclix_var;
	ap_uint<1> gen360_cyclix_var;
	ap_uint<1> gen361_cyclix_var;
	ap_uint<1> gen362_cyclix_var;
	ap_uint<1> gen363_cyclix_var;
	ap_uint<1> gen364_cyclix_var;
	ap_uint<1> gen365_cyclix_var;
	ap_uint<1> gen366_cyclix_var;
	ap_uint<1> gen367_cyclix_var;
	ap_uint<1> gen368_cyclix_var;
	ap_uint<1> gen369_cyclix_var;
	ap_uint<1> gen370_cyclix_var;
	ap_uint<1> gen371_cyclix_var;
	ap_uint<1> gen372_cyclix_var;
	ap_uint<1> gen373_cyclix_var;
	ap_uint<1> gen374_cyclix_var;
	ap_uint<1> gen375_cyclix_var;
	ap_uint<1> gen376_cyclix_var;
	ap_uint<1> gen377_cyclix_var;
	ap_uint<1> gen378_cyclix_var;
	ap_uint<1> gen379_cyclix_var;
	ap_uint<1> gen380_cyclix_var;
	ap_uint<1> gen381_cyclix_var;
	ap_uint<1> gen382_cyclix_var;
	ap_uint<1> gen383_cyclix_var;
	ap_uint<1> gen384_cyclix_var;
	ap_uint<1> gen385_cyclix_var;
	ap_uint<1> gen386_cyclix_var;
	ap_uint<1> gen387_cyclix_var;
	ap_uint<1> gen388_cyclix_var;
	ap_uint<1> gen389_cyclix_var;
	ap_uint<1> gen390_cyclix_var;
	ap_uint<1> gen391_cyclix_var;
	ap_uint<1> gen392_cyclix_var;
	ap_uint<1> gen393_cyclix_var;
	ap_uint<1> gen394_cyclix_var;
	ap_uint<1> gen395_cyclix_var;
	ap_uint<1> gen396_cyclix_var;
	ap_uint<1> gen397_cyclix_var;
	ap_uint<1> gen398_cyclix_var;
	ap_uint<1> gen399_cyclix_var;
	ap_uint<1> gen400_cyclix_var;
	ap_uint<1> gen401_cyclix_var;
	ap_uint<1> gen402_cyclix_var;
	ap_uint<1> gen403_cyclix_var;

	if (geninit) {
		genpsticky_glbl_pc = ap_uint<32>(512);
		genpsticky_glbl_regfile[1] = ap_uint<32>(0);
		genpsticky_glbl_regfile[2] = ap_uint<32>(0);
		genpsticky_glbl_regfile[3] = ap_uint<32>(0);
		genpsticky_glbl_regfile[4] = ap_uint<32>(0);
		genpsticky_glbl_regfile[5] = ap_uint<32>(0);
		genpsticky_glbl_regfile[6] = ap_uint<32>(0);
		genpsticky_glbl_regfile[7] = ap_uint<32>(0);
		genpsticky_glbl_regfile[8] = ap_uint<32>(0);
		genpsticky_glbl_regfile[9] = ap_uint<32>(0);
		genpsticky_glbl_regfile[10] = ap_uint<32>(0);
		genpsticky_glbl_regfile[11] = ap_uint<32>(0);
		genpsticky_glbl_regfile[12] = ap_uint<32>(0);
		genpsticky_glbl_regfile[13] = ap_uint<32>(0);
		genpsticky_glbl_regfile[14] = ap_uint<32>(0);
		genpsticky_glbl_regfile[15] = ap_uint<32>(0);
		genpsticky_glbl_regfile[16] = ap_uint<32>(0);
		genpsticky_glbl_regfile[17] = ap_uint<32>(0);
		genpsticky_glbl_regfile[18] = ap_uint<32>(0);
		genpsticky_glbl_regfile[19] = ap_uint<32>(0);
		genpsticky_glbl_regfile[20] = ap_uint<32>(0);
		genpsticky_glbl_regfile[21] = ap_uint<32>(0);
		genpsticky_glbl_regfile[22] = ap_uint<32>(0);
		genpsticky_glbl_regfile[23] = ap_uint<32>(0);
		genpsticky_glbl_regfile[24] = ap_uint<32>(0);
		genpsticky_glbl_regfile[25] = ap_uint<32>(0);
		genpsticky_glbl_regfile[26] = ap_uint<32>(0);
		genpsticky_glbl_regfile[27] = ap_uint<32>(0);
		genpsticky_glbl_regfile[28] = ap_uint<32>(0);
		genpsticky_glbl_regfile[29] = ap_uint<32>(0);
		genpsticky_glbl_regfile[30] = ap_uint<32>(0);
		genpsticky_glbl_regfile[31] = ap_uint<32>(0);
		genpsticky_glbl_jump_req_cmd = ap_uint<32>(0);
		genpsticky_glbl_jump_vector_cmd = ap_uint<32>(0);
		genpsticky_glbl_CSR_MCAUSE = ap_uint<32>(0);
		genpsticky_glbl_MIRQEN = ap_uint<32>(1);
		genpsticky_glbl_MRETADDR = ap_uint<32>(0);
		genmcopipe_instr_mem_wr_done = ap_uint<32>(0);
		genmcopipe_instr_mem_rd_done = ap_uint<32>(0);
		genmcopipe_instr_mem_full_flag = ap_uint<32>(0);
		genmcopipe_instr_mem_empty_flag = ap_uint<32>(1);
		genmcopipe_instr_mem_wr_ptr = ap_uint<32>(0);
		genmcopipe_instr_mem_rd_ptr = ap_uint<32>(0);
		genmcopipe_data_mem_wr_done = ap_uint<32>(0);
		genmcopipe_data_mem_rd_done = ap_uint<32>(0);
		genmcopipe_data_mem_full_flag = ap_uint<32>(0);
		genmcopipe_data_mem_empty_flag = ap_uint<32>(1);
		genmcopipe_data_mem_wr_ptr = ap_uint<32>(0);
		genmcopipe_data_mem_rd_ptr = ap_uint<32>(0);
		genmcopipe_coproc_M_if_wr_done = ap_uint<32>(0);
		genmcopipe_coproc_M_if_rd_done = ap_uint<32>(0);
		genmcopipe_coproc_M_if_full_flag = ap_uint<32>(0);
		genmcopipe_coproc_M_if_empty_flag = ap_uint<32>(1);
		genmcopipe_coproc_M_if_wr_ptr = ap_uint<32>(0);
		genmcopipe_coproc_M_if_rd_ptr = ap_uint<32>(0);
		genmcopipe_coproc_custom0_if_wr_done = ap_uint<32>(0);
		genmcopipe_coproc_custom0_if_rd_done = ap_uint<32>(0);
		genmcopipe_coproc_custom0_if_full_flag = ap_uint<32>(0);
		genmcopipe_coproc_custom0_if_empty_flag = ap_uint<32>(1);
		genmcopipe_coproc_custom0_if_wr_ptr = ap_uint<32>(0);
		genmcopipe_coproc_custom0_if_rd_ptr = ap_uint<32>(0);
		genpstage_IFETCH_TRX_BUF = ap_uint<32>(0);
		genpstage_IFETCH_TRX_BUF_COUNTER = ap_uint<32>(0);
		genpstage_IFETCH_TRX_BUF_COUNTER_NEMPTY = ap_uint<32>(0);
		genpstage_IFETCH_TRX_BUF_COUNTER_FULL = ap_uint<32>(0);
		genpstage_IFETCH_genctrl_stalled_glbl = ap_uint<32>(0);
		genpstage_EXEC_TRX_BUF = ap_uint<32>(0);
		genpstage_EXEC_TRX_BUF_COUNTER = ap_uint<32>(0);
		genpstage_EXEC_TRX_BUF_COUNTER_NEMPTY = ap_uint<32>(0);
		genpstage_EXEC_TRX_BUF_COUNTER_FULL = ap_uint<32>(0);
		genpstage_EXEC_genctrl_stalled_glbl = ap_uint<32>(0);

	} else {
gen250_cyclix_var = genpsticky_glbl_regfile;
		// mcopipe processing
		genmcopipe_instr_mem_wr_done = ap_uint<32>(0);
		genmcopipe_instr_mem_rd_done = ap_uint<32>(0);
		genmcopipe_instr_mem_wr_ptr_next = (genmcopipe_instr_mem_wr_ptr + ap_uint<32>(1));
		genmcopipe_instr_mem_rd_ptr_next = (genmcopipe_instr_mem_rd_ptr + ap_uint<32>(1));
		genmcopipe_data_mem_wr_done = ap_uint<32>(0);
		genmcopipe_data_mem_rd_done = ap_uint<32>(0);
		genmcopipe_data_mem_wr_ptr_next = (genmcopipe_data_mem_wr_ptr + ap_uint<32>(1));
		genmcopipe_data_mem_rd_ptr_next = (genmcopipe_data_mem_rd_ptr + ap_uint<32>(1));
		genmcopipe_coproc_M_if_wr_done = ap_uint<32>(0);
		genmcopipe_coproc_M_if_rd_done = ap_uint<32>(0);
		genmcopipe_coproc_M_if_wr_ptr_next = (genmcopipe_coproc_M_if_wr_ptr + ap_uint<32>(1));
		genmcopipe_coproc_M_if_rd_ptr_next = (genmcopipe_coproc_M_if_rd_ptr + ap_uint<32>(1));
		genmcopipe_coproc_custom0_if_wr_done = ap_uint<32>(0);
		genmcopipe_coproc_custom0_if_rd_done = ap_uint<32>(0);
		genmcopipe_coproc_custom0_if_wr_ptr_next = (genmcopipe_coproc_custom0_if_wr_ptr + ap_uint<32>(1));
		genmcopipe_coproc_custom0_if_rd_ptr_next = (genmcopipe_coproc_custom0_if_rd_ptr + ap_uint<32>(1));
		// logic of stages
		// #### Stage processing: EXEC ####
		genpstage_EXEC_genctrl_succ = ap_uint<32>(0);
		genpstage_EXEC_genctrl_working = ap_uint<32>(0);
		gen202_cyclix_var = genpstage_EXEC_genctrl_stalled_glbl;
		if (gen202_cyclix_var) {
			genpstage_EXEC_genctrl_new = ap_uint<32>(0);
			genpstage_EXEC_genctrl_stalled_glbl = ap_uint<32>(0);
			genpstage_EXEC_genctrl_active = ap_uint<32>(1);
		}
		gen203_cyclix_var = ap_uint<1>(0);
		gen203_cyclix_var = (gen203_cyclix_var || gen202_cyclix_var);
		gen203_cyclix_var = !gen203_cyclix_var;
		if (gen203_cyclix_var) {
			genpstage_EXEC_genctrl_active = genpstage_EXEC_TRX_BUF_COUNTER_NEMPTY;
			genpstage_EXEC_genctrl_new = genpstage_EXEC_genctrl_active;
		}
		genpstage_EXEC_genctrl_occupied = genpstage_EXEC_genctrl_active;
		genpstage_EXEC_genctrl_finish = ap_uint<32>(0);
		genpstage_EXEC_genpctrl_flushreq = ap_uint<32>(0);
		gen204_cyclix_var = genpstage_EXEC_genctrl_occupied;
		if (gen204_cyclix_var) {
			// Initializing new newaccums descriptors ####
			gen205_cyclix_var = genpstage_EXEC_genctrl_new;
			if (gen205_cyclix_var) {
				genpstage_EXEC_TRX_BUF = ap_uint<32>(0);
				genpstage_EXEC_TRX_BUF = ap_uint<32>(0);
				genpstage_EXEC_TRX_BUF = ap_uint<32>(0);
				genpstage_EXEC_TRX_BUF = ap_uint<32>(0);
				genpstage_EXEC_TRX_BUF = ap_uint<32>(0);
			}
			// Fetching locals from src_glbls
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_BUF[0].irq_mcause;
			genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_BUF[0].irq_recv;
			genpstage_EXEC_TRX_LOCAL = '{default:ap_uint<32>(0)};
			genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_BUF[0].Ext_coproc_req_done;
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_BUF[0].jump_req_done;
			genpstage_EXEC_TRX_LOCAL = '{default:ap_uint<32>(0)};
			genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_BUF[0].data_req_done;
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_BUF[0].curinstr_addr;
			genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_BUF[0].nextinstr_addr;
			// Acquiring mcopipe rdata
			gen206_cyclix_var = genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_coproc_M_if.rdreq_pending;
			if (gen206_cyclix_var) {
				gen207_cyclix_var = (genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_coproc_M_if.if_id == ap_uint<1>(0));
				gen208_cyclix_var = gen207_cyclix_var;
				if (gen208_cyclix_var) {
					gen209_cyclix_var = (genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_coproc_M_if.tid == genmcopipe_coproc_M_if_rd_ptr);
					gen210_cyclix_var = gen209_cyclix_var;
					if (gen210_cyclix_var) {
						gen211_cyclix_var = genmcopipe_coproc_M_if_resp.read_nb(gen312_pipex_mcopipe_rdata);
						gen212_cyclix_var = gen211_cyclix_var;
						if (gen212_cyclix_var) {
							genpstage_EXEC_TRX_BUF = ap_uint<32>(0);
							genpstage_EXEC_TRX_BUF = ap_uint<32>(1);
							genpstage_EXEC_TRX_BUF = gen312_pipex_mcopipe_rdata;
							genmcopipe_coproc_M_if_rd_done = ap_uint<32>(1);
						}
					}
				}
				gen213_cyclix_var = (genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_coproc_M_if.if_id == ap_uint<1>(1));
				gen214_cyclix_var = gen213_cyclix_var;
				if (gen214_cyclix_var) {
					gen215_cyclix_var = (genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_coproc_M_if.tid == genmcopipe_coproc_custom0_if_rd_ptr);
					gen216_cyclix_var = gen215_cyclix_var;
					if (gen216_cyclix_var) {
						gen217_cyclix_var = genmcopipe_coproc_custom0_if_resp.read_nb(gen313_pipex_mcopipe_rdata);
						gen218_cyclix_var = gen217_cyclix_var;
						if (gen218_cyclix_var) {
							genpstage_EXEC_TRX_BUF = ap_uint<32>(0);
							genpstage_EXEC_TRX_BUF = ap_uint<32>(1);
							genpstage_EXEC_TRX_BUF = gen313_pipex_mcopipe_rdata;
							genmcopipe_coproc_custom0_if_rd_done = ap_uint<32>(1);
						}
					}
				}
			}
			gen219_cyclix_var = genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_data_mem.rdreq_pending;
			if (gen219_cyclix_var) {
				gen220_cyclix_var = (genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_data_mem.if_id == ap_uint<1>(0));
				gen221_cyclix_var = gen220_cyclix_var;
				if (gen221_cyclix_var) {
					gen222_cyclix_var = (genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_data_mem.tid == genmcopipe_data_mem_rd_ptr);
					gen223_cyclix_var = gen222_cyclix_var;
					if (gen223_cyclix_var) {
						gen224_cyclix_var = genmcopipe_data_mem_resp.read_nb(gen314_pipex_mcopipe_rdata);
						gen225_cyclix_var = gen224_cyclix_var;
						if (gen225_cyclix_var) {
							genpstage_EXEC_TRX_BUF = ap_uint<32>(0);
							genpstage_EXEC_TRX_BUF = ap_uint<32>(1);
							genpstage_EXEC_TRX_BUF = gen314_pipex_mcopipe_rdata;
							genmcopipe_data_mem_rd_done = ap_uint<32>(1);
						}
					}
				}
			}
			gen226_cyclix_var = genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_instr_mem.rdreq_pending;
			if (gen226_cyclix_var) {
				gen227_cyclix_var = (genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_instr_mem.if_id == ap_uint<1>(0));
				gen228_cyclix_var = gen227_cyclix_var;
				if (gen228_cyclix_var) {
					gen229_cyclix_var = (genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_instr_mem.tid == genmcopipe_instr_mem_rd_ptr);
					gen230_cyclix_var = gen229_cyclix_var;
					if (gen230_cyclix_var) {
						gen231_cyclix_var = genmcopipe_instr_mem_resp.read_nb(gen315_pipex_mcopipe_rdata);
						gen232_cyclix_var = gen231_cyclix_var;
						if (gen232_cyclix_var) {
							genpstage_EXEC_TRX_BUF = ap_uint<32>(0);
							genpstage_EXEC_TRX_BUF = ap_uint<32>(1);
							genpstage_EXEC_TRX_BUF = gen315_pipex_mcopipe_rdata;
							genmcopipe_instr_mem_rd_done = ap_uint<32>(1);
						}
					}
				}
			}
			// Pipeline flush processing
			gen233_cyclix_var = genpstage_EXEC_genpctrl_flushreq;
			if (gen233_cyclix_var) {
				genpstage_EXEC_genctrl_active = ap_uint<32>(0);
			}
		}
		// Saving succ targets
		// Generating payload
		gen234_cyclix_var = genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_instr_mem.resp_done;
		if (gen234_cyclix_var) {
			genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_instr_mem.rdata;
		}
		gen165_pipex_var = genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_instr_mem.resp_done;
		gen166_pipex_var = ~gen165_pipex_var;
		gen167_pipex_var = gen166_pipex_var;
		gen235_cyclix_var = gen167_pipex_var;
		if (gen235_cyclix_var) {
			gen236_cyclix_var = genpstage_EXEC_genctrl_active;
			if (gen236_cyclix_var) {
				genpstage_EXEC_genctrl_stalled_glbl = ap_uint<32>(1);
			}
			genpstage_EXEC_genctrl_active = ap_uint<32>(0);
		}
		genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.instr_code[6:0];
		genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
		genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.instr_code[19:15];
		genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.instr_code[24:20];
		genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.instr_code[11:7];
		genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.instr_code[14:12];
		genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.instr_code[31:25];
		genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.instr_code[24:20];
		genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.instr_code[27:24];
		genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.instr_code[23:20];
		genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.instr_code[31:20];
		genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.instr_code[19:15];
		gen168_pipex_var = genpstage_EXEC_TRX_LOCAL.instr_code[31:20];
		gen169_pipex_var = gen168_pipex_var[31];
		gen170_pipex_var = gen169_pipex_var.concat((ap_uint<31>)gen169_pipex_var.concat((ap_uint<30>)gen169_pipex_var.concat((ap_uint<29>)gen169_pipex_var.concat((ap_uint<28>)gen169_pipex_var.concat((ap_uint<27>)gen169_pipex_var.concat((ap_uint<26>)gen169_pipex_var.concat((ap_uint<25>)gen169_pipex_var.concat((ap_uint<24>)gen169_pipex_var.concat((ap_uint<23>)gen169_pipex_var.concat((ap_uint<22>)gen169_pipex_var.concat((ap_uint<21>)gen169_pipex_var.concat((ap_uint<20>)gen169_pipex_var.concat((ap_uint<19>)gen169_pipex_var.concat((ap_uint<18>)gen169_pipex_var.concat((ap_uint<17>)gen169_pipex_var.concat((ap_uint<16>)gen169_pipex_var.concat((ap_uint<15>)gen169_pipex_var.concat((ap_uint<14>)gen169_pipex_var.concat((ap_uint<13>)gen169_pipex_var.concat((ap_uint<12>)genpstage_EXEC_TRX_LOCAL.instr_code[31:20]))))))))))))))))))));
		genpstage_EXEC_TRX_LOCAL = gen170_pipex_var;
		gen171_pipex_var = genpstage_EXEC_TRX_LOCAL.instr_code[31:25].concat((ap_uint<5>)genpstage_EXEC_TRX_LOCAL.instr_code[11:7]);
		gen172_pipex_var = gen171_pipex_var[11];
		gen173_pipex_var = gen172_pipex_var.concat((ap_uint<31>)gen172_pipex_var.concat((ap_uint<30>)gen172_pipex_var.concat((ap_uint<29>)gen172_pipex_var.concat((ap_uint<28>)gen172_pipex_var.concat((ap_uint<27>)gen172_pipex_var.concat((ap_uint<26>)gen172_pipex_var.concat((ap_uint<25>)gen172_pipex_var.concat((ap_uint<24>)gen172_pipex_var.concat((ap_uint<23>)gen172_pipex_var.concat((ap_uint<22>)gen172_pipex_var.concat((ap_uint<21>)gen172_pipex_var.concat((ap_uint<20>)gen172_pipex_var.concat((ap_uint<19>)gen172_pipex_var.concat((ap_uint<18>)gen172_pipex_var.concat((ap_uint<17>)gen172_pipex_var.concat((ap_uint<16>)gen172_pipex_var.concat((ap_uint<15>)gen172_pipex_var.concat((ap_uint<14>)gen172_pipex_var.concat((ap_uint<13>)gen172_pipex_var.concat((ap_uint<12>)gen171_pipex_var))))))))))))))))))));
		genpstage_EXEC_TRX_LOCAL = gen173_pipex_var;
		gen174_pipex_var = genpstage_EXEC_TRX_LOCAL.instr_code[31].concat((ap_uint<12>)genpstage_EXEC_TRX_LOCAL.instr_code[7].concat((ap_uint<11>)genpstage_EXEC_TRX_LOCAL.instr_code[30:25].concat((ap_uint<5>)genpstage_EXEC_TRX_LOCAL.instr_code[11:8].concat((ap_uint<1>)ap_uint<1>(0)))));
		gen175_pipex_var = gen174_pipex_var[12];
		gen176_pipex_var = gen175_pipex_var.concat((ap_uint<31>)gen175_pipex_var.concat((ap_uint<30>)gen175_pipex_var.concat((ap_uint<29>)gen175_pipex_var.concat((ap_uint<28>)gen175_pipex_var.concat((ap_uint<27>)gen175_pipex_var.concat((ap_uint<26>)gen175_pipex_var.concat((ap_uint<25>)gen175_pipex_var.concat((ap_uint<24>)gen175_pipex_var.concat((ap_uint<23>)gen175_pipex_var.concat((ap_uint<22>)gen175_pipex_var.concat((ap_uint<21>)gen175_pipex_var.concat((ap_uint<20>)gen175_pipex_var.concat((ap_uint<19>)gen175_pipex_var.concat((ap_uint<18>)gen175_pipex_var.concat((ap_uint<17>)gen175_pipex_var.concat((ap_uint<16>)gen175_pipex_var.concat((ap_uint<15>)gen175_pipex_var.concat((ap_uint<14>)gen175_pipex_var.concat((ap_uint<13>)gen174_pipex_var)))))))))))))))))));
		genpstage_EXEC_TRX_LOCAL = gen176_pipex_var;
		gen177_pipex_var = genpstage_EXEC_TRX_LOCAL.instr_code[31:12].concat((ap_uint<12>)ap_uint<12>(0));
		genpstage_EXEC_TRX_LOCAL = gen177_pipex_var;
		gen178_pipex_var = genpstage_EXEC_TRX_LOCAL.instr_code[31].concat((ap_uint<20>)genpstage_EXEC_TRX_LOCAL.instr_code[19:12].concat((ap_uint<12>)genpstage_EXEC_TRX_LOCAL.instr_code[20].concat((ap_uint<11>)genpstage_EXEC_TRX_LOCAL.instr_code[30:21].concat((ap_uint<1>)ap_uint<1>(0)))));
		gen179_pipex_var = gen178_pipex_var[20];
		gen180_pipex_var = gen179_pipex_var.concat((ap_uint<31>)gen179_pipex_var.concat((ap_uint<30>)gen179_pipex_var.concat((ap_uint<29>)gen179_pipex_var.concat((ap_uint<28>)gen179_pipex_var.concat((ap_uint<27>)gen179_pipex_var.concat((ap_uint<26>)gen179_pipex_var.concat((ap_uint<25>)gen179_pipex_var.concat((ap_uint<24>)gen179_pipex_var.concat((ap_uint<23>)gen179_pipex_var.concat((ap_uint<22>)gen179_pipex_var.concat((ap_uint<21>)gen178_pipex_var)))))))))));
		genpstage_EXEC_TRX_LOCAL = gen180_pipex_var;
		switch (genpstage_EXEC_TRX_LOCAL) {
			case 55:
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.immediate_U;
				break;
			case 23:
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(2);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.immediate_U;
				break;
			case 111:
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(2);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(4);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.immediate_J;
				break;
			case 103:
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(4);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.immediate_I;
				break;
			case 99:
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.immediate_B;
				gen181_pipex_var = (genpstage_EXEC_TRX_LOCAL.funct3 == ap_uint<32>(6));
				gen182_pipex_var = (genpstage_EXEC_TRX_LOCAL.funct3 == ap_uint<32>(7));
				gen183_pipex_var = (gen181_pipex_var | gen182_pipex_var);
				gen184_pipex_var = gen183_pipex_var;
				gen237_cyclix_var = gen184_pipex_var;
				if (gen237_cyclix_var) {
					genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				}
				break;
			case 3:
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(5);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.immediate_I;
				break;
			case 35:
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.immediate_S;
				break;
			case 19:
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.immediate_I;
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				switch (genpstage_EXEC_TRX_LOCAL) {
					case 0:
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						break;
					case 1:
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(4);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						gen185_pipex_var = ap_uint<27>(0).concat((ap_uint<5>)genpstage_EXEC_TRX_LOCAL.instr_code[24:20]);
						genpstage_EXEC_TRX_LOCAL = gen185_pipex_var;
						break;
					case 2:
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(2);
						break;
					case 3:
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(2);
						break;
					case 4:
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(7);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						break;
					case 5:
						gen186_pipex_var = genpstage_EXEC_TRX_LOCAL.instr_code[30];
						gen238_cyclix_var = gen186_pipex_var;
						if (gen238_cyclix_var) {
							genpstage_EXEC_TRX_LOCAL = ap_uint<32>(6);
						}
						gen187_pipex_var = ap_uint<1>(0);
						gen187_pipex_var = (gen187_pipex_var || gen186_pipex_var);
						gen187_pipex_var = !gen187_pipex_var;
						gen239_cyclix_var = gen187_pipex_var;
						if (gen239_cyclix_var) {
							genpstage_EXEC_TRX_LOCAL = ap_uint<32>(5);
						}
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						gen188_pipex_var = ap_uint<27>(0).concat((ap_uint<5>)genpstage_EXEC_TRX_LOCAL.instr_code[24:20]);
						genpstage_EXEC_TRX_LOCAL = gen188_pipex_var;
						break;
					case 6:
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(3);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						break;
					case 7:
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(2);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						break;
				}
				break;
			case 51:
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				switch (genpstage_EXEC_TRX_LOCAL) {
					case 0:
						gen189_pipex_var = genpstage_EXEC_TRX_LOCAL.instr_code[30];
						gen240_cyclix_var = gen189_pipex_var;
						if (gen240_cyclix_var) {
							genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						}
						gen190_pipex_var = ap_uint<1>(0);
						gen190_pipex_var = (gen190_pipex_var || gen189_pipex_var);
						gen190_pipex_var = !gen190_pipex_var;
						gen241_cyclix_var = gen190_pipex_var;
						if (gen241_cyclix_var) {
							genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
						}
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						break;
					case 1:
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(4);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						break;
					case 2:
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(2);
						break;
					case 3:
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(2);
						break;
					case 4:
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(7);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						break;
					case 5:
						gen191_pipex_var = genpstage_EXEC_TRX_LOCAL.instr_code[30];
						gen242_cyclix_var = gen191_pipex_var;
						if (gen242_cyclix_var) {
							genpstage_EXEC_TRX_LOCAL = ap_uint<32>(6);
						}
						gen192_pipex_var = ap_uint<1>(0);
						gen192_pipex_var = (gen192_pipex_var || gen191_pipex_var);
						gen192_pipex_var = !gen192_pipex_var;
						gen243_cyclix_var = gen192_pipex_var;
						if (gen243_cyclix_var) {
							genpstage_EXEC_TRX_LOCAL = ap_uint<32>(5);
						}
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						break;
					case 6:
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(3);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						break;
					case 7:
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(2);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						break;
				}
				gen193_pipex_var = (genpstage_EXEC_TRX_LOCAL.funct7 == ap_uint<32>(1));
				gen194_pipex_var = gen193_pipex_var;
				gen244_cyclix_var = gen194_pipex_var;
				if (gen244_cyclix_var) {
					genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
					genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
					genpstage_EXEC_TRX_LOCAL = ap_uint<32>(7);
				}
				break;
			case 15:
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				break;
			case 115:
				switch (genpstage_EXEC_TRX_LOCAL) {
					case 0:
						gen195_pipex_var = genpstage_EXEC_TRX_LOCAL.instr_code[20];
						gen245_cyclix_var = gen195_pipex_var;
						if (gen245_cyclix_var) {
							genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						}
						gen196_pipex_var = ap_uint<1>(0);
						gen196_pipex_var = (gen196_pipex_var || gen195_pipex_var);
						gen196_pipex_var = !gen196_pipex_var;
						gen246_cyclix_var = gen196_pipex_var;
						if (gen246_cyclix_var) {
							genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						}
						break;
					case 1:
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(6);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(2);
						break;
					case 2:
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(6);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(3);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(2);
						break;
					case 3:
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(6);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(8);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(2);
						break;
					case 5:
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(2);
						gen197_pipex_var = ap_uint<27>(0).concat((ap_uint<5>)genpstage_EXEC_TRX_LOCAL.zimm);
						genpstage_EXEC_TRX_LOCAL = gen197_pipex_var;
						break;
					case 6:
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(6);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(8);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(2);
						gen198_pipex_var = ap_uint<27>(0).concat((ap_uint<5>)genpstage_EXEC_TRX_LOCAL.zimm);
						genpstage_EXEC_TRX_LOCAL = gen198_pipex_var;
						break;
					case 7:
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(6);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(8);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(2);
						gen199_pipex_var = ap_uint<27>(0).concat((ap_uint<5>)genpstage_EXEC_TRX_LOCAL.zimm);
						genpstage_EXEC_TRX_LOCAL = gen199_pipex_var;
						break;
				}
				break;
			case 11:
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(7);
				break;
		}
		gen200_pipex_var = genpstage_EXEC_TRX_LOCAL.mem_req;
		gen247_cyclix_var = gen200_pipex_var;
		if (gen247_cyclix_var) {
			switch (genpstage_EXEC_TRX_LOCAL) {
				case 0:
					genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
					genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
					break;
				case 1:
					genpstage_EXEC_TRX_LOCAL = ap_uint<32>(3);
					genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
					break;
				case 2:
					genpstage_EXEC_TRX_LOCAL = ap_uint<32>(15);
					break;
				case 4:
					genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
					break;
				case 5:
					genpstage_EXEC_TRX_LOCAL = ap_uint<32>(3);
					break;
			}
		}
		gen201_pipex_var = (genpstage_EXEC_TRX_LOCAL.instr_code == ap_uint<32>(807403635));
		gen202_pipex_var = gen201_pipex_var;
		gen248_cyclix_var = gen202_pipex_var;
		if (gen248_cyclix_var) {
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
			genpstage_EXEC_TRX_LOCAL = genpsticky_glbl_MRETADDR;
		}
		gen203_pipex_var = (genpstage_EXEC_TRX_LOCAL.rd_addr == ap_uint<32>(0));
		gen204_pipex_var = gen203_pipex_var;
		gen249_cyclix_var = gen204_pipex_var;
		if (gen249_cyclix_var) {
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
		}
		gen205_pipex_var = gen48_cyclix_readPrev[1];
		gen205_pipex_var = gen48_cyclix_readPrev[2];
		gen205_pipex_var = gen48_cyclix_readPrev[3];
		gen205_pipex_var = gen48_cyclix_readPrev[4];
		gen205_pipex_var = gen48_cyclix_readPrev[5];
		gen205_pipex_var = gen48_cyclix_readPrev[6];
		gen205_pipex_var = gen48_cyclix_readPrev[7];
		gen205_pipex_var = gen48_cyclix_readPrev[8];
		gen205_pipex_var = gen48_cyclix_readPrev[9];
		gen205_pipex_var = gen48_cyclix_readPrev[10];
		gen205_pipex_var = gen48_cyclix_readPrev[11];
		gen205_pipex_var = gen48_cyclix_readPrev[12];
		gen205_pipex_var = gen48_cyclix_readPrev[13];
		gen205_pipex_var = gen48_cyclix_readPrev[14];
		gen205_pipex_var = gen48_cyclix_readPrev[15];
		gen205_pipex_var = gen48_cyclix_readPrev[16];
		gen205_pipex_var = gen48_cyclix_readPrev[17];
		gen205_pipex_var = gen48_cyclix_readPrev[18];
		gen205_pipex_var = gen48_cyclix_readPrev[19];
		gen205_pipex_var = gen48_cyclix_readPrev[20];
		gen205_pipex_var = gen48_cyclix_readPrev[21];
		gen205_pipex_var = gen48_cyclix_readPrev[22];
		gen205_pipex_var = gen48_cyclix_readPrev[23];
		gen205_pipex_var = gen48_cyclix_readPrev[24];
		gen205_pipex_var = gen48_cyclix_readPrev[25];
		gen205_pipex_var = gen48_cyclix_readPrev[26];
		gen205_pipex_var = gen48_cyclix_readPrev[27];
		gen205_pipex_var = gen48_cyclix_readPrev[28];
		gen205_pipex_var = gen48_cyclix_readPrev[29];
		gen205_pipex_var = gen48_cyclix_readPrev[30];
		gen205_pipex_var = gen48_cyclix_readPrev[31];
		genpstage_EXEC_TRX_LOCAL = gen205_pipex_var[genpstage_EXEC_TRX_LOCAL.rs1_addr];
		gen206_pipex_var = gen48_cyclix_readPrev[1];
		gen206_pipex_var = gen48_cyclix_readPrev[2];
		gen206_pipex_var = gen48_cyclix_readPrev[3];
		gen206_pipex_var = gen48_cyclix_readPrev[4];
		gen206_pipex_var = gen48_cyclix_readPrev[5];
		gen206_pipex_var = gen48_cyclix_readPrev[6];
		gen206_pipex_var = gen48_cyclix_readPrev[7];
		gen206_pipex_var = gen48_cyclix_readPrev[8];
		gen206_pipex_var = gen48_cyclix_readPrev[9];
		gen206_pipex_var = gen48_cyclix_readPrev[10];
		gen206_pipex_var = gen48_cyclix_readPrev[11];
		gen206_pipex_var = gen48_cyclix_readPrev[12];
		gen206_pipex_var = gen48_cyclix_readPrev[13];
		gen206_pipex_var = gen48_cyclix_readPrev[14];
		gen206_pipex_var = gen48_cyclix_readPrev[15];
		gen206_pipex_var = gen48_cyclix_readPrev[16];
		gen206_pipex_var = gen48_cyclix_readPrev[17];
		gen206_pipex_var = gen48_cyclix_readPrev[18];
		gen206_pipex_var = gen48_cyclix_readPrev[19];
		gen206_pipex_var = gen48_cyclix_readPrev[20];
		gen206_pipex_var = gen48_cyclix_readPrev[21];
		gen206_pipex_var = gen48_cyclix_readPrev[22];
		gen206_pipex_var = gen48_cyclix_readPrev[23];
		gen206_pipex_var = gen48_cyclix_readPrev[24];
		gen206_pipex_var = gen48_cyclix_readPrev[25];
		gen206_pipex_var = gen48_cyclix_readPrev[26];
		gen206_pipex_var = gen48_cyclix_readPrev[27];
		gen206_pipex_var = gen48_cyclix_readPrev[28];
		gen206_pipex_var = gen48_cyclix_readPrev[29];
		gen206_pipex_var = gen48_cyclix_readPrev[30];
		gen206_pipex_var = gen48_cyclix_readPrev[31];
		genpstage_EXEC_TRX_LOCAL = gen206_pipex_var[genpstage_EXEC_TRX_LOCAL.rs2_addr];
		gen207_pipex_var = (genpstage_EXEC_TRX_LOCAL.rs1_addr == ap_uint<32>(0));
		gen208_pipex_var = gen207_pipex_var;
		gen251_cyclix_var = gen208_pipex_var;
		if (gen251_cyclix_var) {
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
		}
		gen209_pipex_var = (genpstage_EXEC_TRX_LOCAL.rs2_addr == ap_uint<32>(0));
		gen210_pipex_var = gen209_pipex_var;
		gen252_cyclix_var = gen210_pipex_var;
		if (gen252_cyclix_var) {
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
		}
		gen211_pipex_var = genpstage_EXEC_TRX_LOCAL.csrreq;
		gen253_cyclix_var = gen211_pipex_var;
		if (gen253_cyclix_var) {
			genpstage_EXEC_TRX_LOCAL = genpsticky_glbl_CSR_MCAUSE;
		}
		genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.rs1_rdata;
		switch (genpstage_EXEC_TRX_LOCAL) {
			case 1:
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.immediate;
				break;
			case 2:
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.curinstr_addr;
				break;
		}
		genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.rs2_rdata;
		switch (genpstage_EXEC_TRX_LOCAL) {
			case 1:
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.immediate;
				break;
			case 2:
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.csr_rdata;
				break;
		}
		gen212_pipex_var = genpstage_EXEC_TRX_LOCAL.alu_unsigned;
		gen254_cyclix_var = gen212_pipex_var;
		if (gen254_cyclix_var) {
			gen213_pipex_var = ap_uint<1>(0).concat((ap_uint<32>)genpstage_EXEC_TRX_LOCAL.alu_op1);
			genpstage_EXEC_TRX_LOCAL = gen213_pipex_var;
			gen214_pipex_var = ap_uint<1>(0).concat((ap_uint<32>)genpstage_EXEC_TRX_LOCAL.alu_op2);
			genpstage_EXEC_TRX_LOCAL = gen214_pipex_var;
		}
		gen215_pipex_var = ap_uint<1>(0);
		gen215_pipex_var = (gen215_pipex_var || gen212_pipex_var);
		gen215_pipex_var = !gen215_pipex_var;
		gen255_cyclix_var = gen215_pipex_var;
		if (gen255_cyclix_var) {
			gen216_pipex_var = genpstage_EXEC_TRX_LOCAL[31];
			gen217_pipex_var = gen216_pipex_var.concat((ap_uint<32>)genpstage_EXEC_TRX_LOCAL.alu_op1);
			genpstage_EXEC_TRX_LOCAL = gen217_pipex_var;
			gen218_pipex_var = genpstage_EXEC_TRX_LOCAL[31];
			gen219_pipex_var = gen218_pipex_var.concat((ap_uint<32>)genpstage_EXEC_TRX_LOCAL.alu_op2);
			genpstage_EXEC_TRX_LOCAL = gen219_pipex_var;
		}
		gen220_pipex_var = genpsticky_glbl_MIRQEN;
		gen256_cyclix_var = gen220_pipex_var;
		if (gen256_cyclix_var) {
			gen221_pipex_var = ~genpstage_EXEC_TRX_LOCAL.irq_recv;
			gen222_pipex_var = gen221_pipex_var;
			gen257_cyclix_var = gen222_pipex_var;
			if (gen257_cyclix_var) {
				gen258_cyclix_var = genpstage_EXEC_genctrl_active;
				if (gen258_cyclix_var) {
					gen259_cyclix_var = irq_fifo.read_nb(genpstage_EXEC_TRX_LOCAL);
					gen223_pipex_var = gen259_cyclix_var;
				}
				genpstage_EXEC_TRX_LOCAL = gen223_pipex_var;
				gen260_cyclix_var = genpstage_EXEC_genctrl_active;
				if (gen260_cyclix_var) {
					genpstage_EXEC_TRX_BUF = gen223_pipex_var;
				}
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.irq_mcause;
				gen261_cyclix_var = genpstage_EXEC_genctrl_active;
				if (gen261_cyclix_var) {
					genpstage_EXEC_TRX_BUF = genpstage_EXEC_TRX_LOCAL.irq_mcause;
				}
			}
			gen224_pipex_var = genpstage_EXEC_TRX_LOCAL.irq_recv;
			gen262_cyclix_var = gen224_pipex_var;
			if (gen262_cyclix_var) {
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(128);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(0);
				gen263_cyclix_var = genpstage_EXEC_genctrl_active;
				if (gen263_cyclix_var) {
					genpsticky_glbl_MIRQEN = ap_uint<32>(0);
				}
				gen264_cyclix_var = genpstage_EXEC_genctrl_active;
				if (gen264_cyclix_var) {
					genpsticky_glbl_CSR_MCAUSE = genpstage_EXEC_TRX_LOCAL.irq_mcause;
				}
				gen265_cyclix_var = genpstage_EXEC_genctrl_active;
				if (gen265_cyclix_var) {
					genpsticky_glbl_MRETADDR = genpstage_EXEC_TRX_LOCAL.curinstr_addr;
				}
			}
		}
		gen225_pipex_var = genpstage_EXEC_TRX_LOCAL.mret_req;
		gen266_cyclix_var = gen225_pipex_var;
		if (gen266_cyclix_var) {
			gen267_cyclix_var = genpstage_EXEC_genctrl_active;
			if (gen267_cyclix_var) {
				genpsticky_glbl_MIRQEN = ap_uint<32>(1);
			}
		}
		genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.instr_code;
		genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.alu_op1;
		genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.alu_op2;
		gen226_pipex_var = ~genpstage_EXEC_TRX_LOCAL.Ext_coproc_req_done;
		gen227_pipex_var = gen226_pipex_var;
		gen268_cyclix_var = gen227_pipex_var;
		if (gen268_cyclix_var) {
			gen228_pipex_var = genpstage_EXEC_TRX_LOCAL.m_ext_req;
			gen269_cyclix_var = gen228_pipex_var;
			if (gen269_cyclix_var) {
				gen270_cyclix_var = genpstage_EXEC_genctrl_active;
				if (gen270_cyclix_var) {
					gen271_cyclix_var = ~genmcopipe_coproc_M_if_full_flag;
					gen272_cyclix_var = gen271_cyclix_var;
					if (gen272_cyclix_var) {
						gen316_pipex_req_struct = ap_uint<32>(0);
						gen316_pipex_req_struct = genpstage_EXEC_TRX_LOCAL.Ext_coproc_busreq;
						gen273_cyclix_var = genmcopipe_coproc_M_if_req.write_nb(gen316_pipex_req_struct);
						gen274_cyclix_var = gen273_cyclix_var;
						if (gen274_cyclix_var) {
							gen229_pipex_var = ap_uint<32>(1);
							gen275_cyclix_var = !ap_uint<32>(0);
							genpstage_EXEC_TRX_BUF = gen275_cyclix_var;
							genpstage_EXEC_TRX_BUF = genmcopipe_coproc_M_if_wr_ptr;
							genpstage_EXEC_TRX_BUF = ap_uint<1>(0);
							gen276_cyclix_var = genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_coproc_M_if.rdreq_pending;
							if (gen276_cyclix_var) {
								genmcopipe_coproc_M_if_wr_done = ap_uint<32>(1);
							}
						}
					}
				}
				genpstage_EXEC_TRX_LOCAL = gen229_pipex_var;
				gen277_cyclix_var = genpstage_EXEC_genctrl_active;
				if (gen277_cyclix_var) {
					genpstage_EXEC_TRX_BUF = gen229_pipex_var;
				}
				gen230_pipex_var = ~genpstage_EXEC_TRX_LOCAL.Ext_coproc_req_done;
				gen231_pipex_var = gen230_pipex_var;
				gen278_cyclix_var = gen231_pipex_var;
				if (gen278_cyclix_var) {
					gen279_cyclix_var = genpstage_EXEC_genctrl_active;
					if (gen279_cyclix_var) {
						genpstage_EXEC_genctrl_stalled_glbl = ap_uint<32>(1);
					}
					genpstage_EXEC_genctrl_active = ap_uint<32>(0);
				}
			}
			gen232_pipex_var = genpstage_EXEC_TRX_LOCAL.custom0_ext_req;
			gen280_cyclix_var = gen232_pipex_var;
			if (gen280_cyclix_var) {
				gen281_cyclix_var = genpstage_EXEC_genctrl_active;
				if (gen281_cyclix_var) {
					gen282_cyclix_var = ~genmcopipe_coproc_custom0_if_full_flag;
					gen283_cyclix_var = gen282_cyclix_var;
					if (gen283_cyclix_var) {
						gen317_pipex_req_struct = ap_uint<32>(0);
						gen317_pipex_req_struct = genpstage_EXEC_TRX_LOCAL.Ext_coproc_busreq;
						gen284_cyclix_var = genmcopipe_coproc_custom0_if_req.write_nb(gen317_pipex_req_struct);
						gen285_cyclix_var = gen284_cyclix_var;
						if (gen285_cyclix_var) {
							gen233_pipex_var = ap_uint<32>(1);
							gen286_cyclix_var = !ap_uint<32>(0);
							genpstage_EXEC_TRX_BUF = gen286_cyclix_var;
							genpstage_EXEC_TRX_BUF = genmcopipe_coproc_custom0_if_wr_ptr;
							genpstage_EXEC_TRX_BUF = ap_uint<1>(1);
							gen287_cyclix_var = genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_coproc_M_if.rdreq_pending;
							if (gen287_cyclix_var) {
								genmcopipe_coproc_custom0_if_wr_done = ap_uint<32>(1);
							}
						}
					}
				}
				genpstage_EXEC_TRX_LOCAL = gen233_pipex_var;
				gen288_cyclix_var = genpstage_EXEC_genctrl_active;
				if (gen288_cyclix_var) {
					genpstage_EXEC_TRX_BUF = gen233_pipex_var;
				}
				gen234_pipex_var = ~genpstage_EXEC_TRX_LOCAL.Ext_coproc_req_done;
				gen235_pipex_var = gen234_pipex_var;
				gen289_cyclix_var = gen235_pipex_var;
				if (gen289_cyclix_var) {
					gen290_cyclix_var = genpstage_EXEC_genctrl_active;
					if (gen290_cyclix_var) {
						genpstage_EXEC_genctrl_stalled_glbl = ap_uint<32>(1);
					}
					genpstage_EXEC_genctrl_active = ap_uint<32>(0);
				}
			}
		}
		genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.alu_op1_wide;
		gen236_pipex_var = genpstage_EXEC_TRX_LOCAL.alu_req;
		gen291_cyclix_var = gen236_pipex_var;
		if (gen291_cyclix_var) {
			switch (genpstage_EXEC_TRX_LOCAL) {
				case 0:
					gen237_pipex_var = (genpstage_EXEC_TRX_LOCAL.alu_op1_wide + genpstage_EXEC_TRX_LOCAL.alu_op2_wide);
					genpstage_EXEC_TRX_LOCAL = gen237_pipex_var;
					break;
				case 1:
					gen238_pipex_var = (genpstage_EXEC_TRX_LOCAL.alu_op1_wide - genpstage_EXEC_TRX_LOCAL.alu_op2_wide);
					genpstage_EXEC_TRX_LOCAL = gen238_pipex_var;
					break;
				case 2:
					gen239_pipex_var = (genpstage_EXEC_TRX_LOCAL.alu_op1_wide & genpstage_EXEC_TRX_LOCAL.alu_op2_wide);
					genpstage_EXEC_TRX_LOCAL = gen239_pipex_var;
					break;
				case 3:
					gen240_pipex_var = (genpstage_EXEC_TRX_LOCAL.alu_op1_wide | genpstage_EXEC_TRX_LOCAL.alu_op2_wide);
					genpstage_EXEC_TRX_LOCAL = gen240_pipex_var;
					break;
				case 4:
					gen241_pipex_var = (genpstage_EXEC_TRX_LOCAL.alu_op1_wide << genpstage_EXEC_TRX_LOCAL.alu_op2_wide);
					genpstage_EXEC_TRX_LOCAL = gen241_pipex_var;
					break;
				case 5:
					gen242_pipex_var = ap_uint<32>(0).concat((ap_uint<32>)genpstage_EXEC_TRX_LOCAL.alu_op1_wide[31:0]);
					gen243_pipex_var = (gen242_pipex_var >> genpstage_EXEC_TRX_LOCAL.alu_op2_wide[4:0]);
					genpstage_EXEC_TRX_LOCAL = gen243_pipex_var;
					break;
				case 6:
					gen244_pipex_var = genpstage_EXEC_TRX_LOCAL.alu_op1_wide[31:0];
					gen245_pipex_var = gen244_pipex_var[31];
					gen246_pipex_var = gen245_pipex_var.concat((ap_uint<63>)gen245_pipex_var.concat((ap_uint<62>)gen245_pipex_var.concat((ap_uint<61>)gen245_pipex_var.concat((ap_uint<60>)gen245_pipex_var.concat((ap_uint<59>)gen245_pipex_var.concat((ap_uint<58>)gen245_pipex_var.concat((ap_uint<57>)gen245_pipex_var.concat((ap_uint<56>)gen245_pipex_var.concat((ap_uint<55>)gen245_pipex_var.concat((ap_uint<54>)gen245_pipex_var.concat((ap_uint<53>)gen245_pipex_var.concat((ap_uint<52>)gen245_pipex_var.concat((ap_uint<51>)gen245_pipex_var.concat((ap_uint<50>)gen245_pipex_var.concat((ap_uint<49>)gen245_pipex_var.concat((ap_uint<48>)gen245_pipex_var.concat((ap_uint<47>)gen245_pipex_var.concat((ap_uint<46>)gen245_pipex_var.concat((ap_uint<45>)gen245_pipex_var.concat((ap_uint<44>)gen245_pipex_var.concat((ap_uint<43>)gen245_pipex_var.concat((ap_uint<42>)gen245_pipex_var.concat((ap_uint<41>)gen245_pipex_var.concat((ap_uint<40>)gen245_pipex_var.concat((ap_uint<39>)gen245_pipex_var.concat((ap_uint<38>)gen245_pipex_var.concat((ap_uint<37>)gen245_pipex_var.concat((ap_uint<36>)gen245_pipex_var.concat((ap_uint<35>)gen245_pipex_var.concat((ap_uint<34>)gen245_pipex_var.concat((ap_uint<33>)gen245_pipex_var.concat((ap_uint<32>)genpstage_EXEC_TRX_LOCAL.alu_op1_wide[31:0]))))))))))))))))))))))))))))))));
					gen247_pipex_var = (gen246_pipex_var >> genpstage_EXEC_TRX_LOCAL.alu_op2_wide[4:0]);
					genpstage_EXEC_TRX_LOCAL = gen247_pipex_var;
					break;
				case 7:
					gen248_pipex_var = (genpstage_EXEC_TRX_LOCAL.alu_op1_wide ^ genpstage_EXEC_TRX_LOCAL.alu_op2_wide);
					genpstage_EXEC_TRX_LOCAL = gen248_pipex_var;
					break;
				case 8:
					gen249_pipex_var = ~genpstage_EXEC_TRX_LOCAL.alu_op2_wide;
					gen250_pipex_var = (genpstage_EXEC_TRX_LOCAL.alu_op1_wide & gen249_pipex_var);
					genpstage_EXEC_TRX_LOCAL = gen250_pipex_var;
					break;
			}
			genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.alu_result_wide[31:0];
			genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.alu_result_wide[32];
			genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.alu_result_wide[31];
			gen251_pipex_var = |genpstage_EXEC_TRX_LOCAL.alu_result;
			gen252_pipex_var = ~gen251_pipex_var;
			genpstage_EXEC_TRX_LOCAL = gen252_pipex_var;
			gen253_pipex_var = ~genpstage_EXEC_TRX_LOCAL.alu_op1[31];
			gen254_pipex_var = ~genpstage_EXEC_TRX_LOCAL.alu_op2[31];
			gen255_pipex_var = (gen253_pipex_var & gen254_pipex_var);
			gen256_pipex_var = (gen255_pipex_var & genpstage_EXEC_TRX_LOCAL.alu_result[31]);
			gen257_pipex_var = ~genpstage_EXEC_TRX_LOCAL.alu_result[31];
			gen258_pipex_var = (genpstage_EXEC_TRX_LOCAL.alu_op1[31] & genpstage_EXEC_TRX_LOCAL.alu_op2[31]);
			gen259_pipex_var = (gen258_pipex_var & gen257_pipex_var);
			gen260_pipex_var = (gen256_pipex_var | gen259_pipex_var);
			genpstage_EXEC_TRX_LOCAL = gen260_pipex_var;
			gen261_pipex_var = genpstage_EXEC_TRX_LOCAL.alu_unsigned;
			gen292_cyclix_var = gen261_pipex_var;
			if (gen292_cyclix_var) {
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.alu_CF;
			}
			gen262_pipex_var = ap_uint<1>(0);
			gen262_pipex_var = (gen262_pipex_var || gen261_pipex_var);
			gen262_pipex_var = !gen262_pipex_var;
			gen293_cyclix_var = gen262_pipex_var;
			if (gen293_cyclix_var) {
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.alu_OF;
			}
		}
		switch (genpstage_EXEC_TRX_LOCAL) {
			case 0:
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.immediate;
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				break;
			case 1:
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.alu_result;
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				break;
			case 2:
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.alu_CF;
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				break;
			case 3:
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.alu_OF;
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				break;
			case 4:
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.nextinstr_addr;
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				break;
			case 6:
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.csr_rdata;
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				break;
		}
		gen263_pipex_var = (genpstage_EXEC_TRX_LOCAL.curinstr_addr + genpstage_EXEC_TRX_LOCAL.immediate);
		genpstage_EXEC_TRX_LOCAL = gen263_pipex_var;
		switch (genpstage_EXEC_TRX_LOCAL) {
			case 0:
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.immediate;
				break;
			case 1:
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.alu_result;
				break;
		}
		gen264_pipex_var = genpstage_EXEC_TRX_LOCAL.jump_req_cond;
		gen294_cyclix_var = gen264_pipex_var;
		if (gen294_cyclix_var) {
			switch (genpstage_EXEC_TRX_LOCAL) {
				case 0:
					gen265_pipex_var = genpstage_EXEC_TRX_LOCAL.alu_ZF;
					gen295_cyclix_var = gen265_pipex_var;
					if (gen295_cyclix_var) {
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.curinstraddr_imm;
					}
					break;
				case 1:
					gen266_pipex_var = ~genpstage_EXEC_TRX_LOCAL.alu_ZF;
					gen267_pipex_var = gen266_pipex_var;
					gen296_cyclix_var = gen267_pipex_var;
					if (gen296_cyclix_var) {
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.curinstraddr_imm;
					}
					break;
				case 4:
					gen268_pipex_var = genpstage_EXEC_TRX_LOCAL.alu_CF;
					gen297_cyclix_var = gen268_pipex_var;
					if (gen297_cyclix_var) {
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.curinstraddr_imm;
					}
					break;
				case 5:
					gen269_pipex_var = ~genpstage_EXEC_TRX_LOCAL.alu_CF;
					gen270_pipex_var = gen269_pipex_var;
					gen298_cyclix_var = gen270_pipex_var;
					if (gen298_cyclix_var) {
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.curinstraddr_imm;
					}
					break;
				case 6:
					gen271_pipex_var = genpstage_EXEC_TRX_LOCAL.alu_CF;
					gen299_cyclix_var = gen271_pipex_var;
					if (gen299_cyclix_var) {
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.curinstraddr_imm;
					}
					break;
				case 7:
					gen272_pipex_var = ~genpstage_EXEC_TRX_LOCAL.alu_CF;
					gen273_pipex_var = gen272_pipex_var;
					gen300_cyclix_var = gen273_pipex_var;
					if (gen300_cyclix_var) {
						genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
						genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.curinstraddr_imm;
					}
					break;
			}
		}
		genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.alu_result;
		genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.rs2_rdata;
		gen274_pipex_var = ~genpstage_EXEC_TRX_LOCAL.jump_req_done;
		gen275_pipex_var = gen274_pipex_var;
		gen301_cyclix_var = gen275_pipex_var;
		if (gen301_cyclix_var) {
			gen302_cyclix_var = genpstage_EXEC_genctrl_active;
			if (gen302_cyclix_var) {
				genpsticky_glbl_jump_req_cmd = genpstage_EXEC_TRX_LOCAL.jump_req;
			}
			gen303_cyclix_var = genpstage_EXEC_genctrl_active;
			if (gen303_cyclix_var) {
				genpsticky_glbl_jump_vector_cmd = genpstage_EXEC_TRX_LOCAL.jump_vector;
			}
			genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
			gen304_cyclix_var = genpstage_EXEC_genctrl_active;
			if (gen304_cyclix_var) {
				genpstage_EXEC_TRX_BUF = ap_uint<32>(1);
			}
		}
		gen276_pipex_var = genpstage_EXEC_TRX_LOCAL.mem_req;
		gen305_cyclix_var = gen276_pipex_var;
		if (gen305_cyclix_var) {
			gen277_pipex_var = ~genpstage_EXEC_TRX_LOCAL.data_req_done;
			gen278_pipex_var = gen277_pipex_var;
			gen306_cyclix_var = gen278_pipex_var;
			if (gen306_cyclix_var) {
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.mem_addr;
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.mem_be;
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.mem_wdata;
				gen307_cyclix_var = genpstage_EXEC_genctrl_active;
				if (gen307_cyclix_var) {
					gen308_cyclix_var = ~genmcopipe_data_mem_full_flag;
					gen309_cyclix_var = gen308_cyclix_var;
					if (gen309_cyclix_var) {
						gen318_pipex_req_struct = genpstage_EXEC_TRX_LOCAL.mem_cmd;
						gen318_pipex_req_struct = genpstage_EXEC_TRX_LOCAL.data_busreq;
						gen310_cyclix_var = genmcopipe_data_mem_req.write_nb(gen318_pipex_req_struct);
						gen311_cyclix_var = gen310_cyclix_var;
						if (gen311_cyclix_var) {
							gen279_pipex_var = ap_uint<32>(1);
							gen312_cyclix_var = !genpstage_EXEC_TRX_LOCAL.mem_cmd;
							genpstage_EXEC_TRX_BUF = gen312_cyclix_var;
							genpstage_EXEC_TRX_BUF = genmcopipe_data_mem_wr_ptr;
							genpstage_EXEC_TRX_BUF = ap_uint<1>(0);
							gen313_cyclix_var = genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_data_mem.rdreq_pending;
							if (gen313_cyclix_var) {
								genmcopipe_data_mem_wr_done = ap_uint<32>(1);
							}
						}
					}
				}
				genpstage_EXEC_TRX_LOCAL = gen279_pipex_var;
				gen314_cyclix_var = genpstage_EXEC_genctrl_active;
				if (gen314_cyclix_var) {
					genpstage_EXEC_TRX_BUF = gen279_pipex_var;
				}
			}
			gen280_pipex_var = ~genpstage_EXEC_TRX_LOCAL.data_req_done;
			gen281_pipex_var = gen280_pipex_var;
			gen315_cyclix_var = gen281_pipex_var;
			if (gen315_cyclix_var) {
				gen316_cyclix_var = genpstage_EXEC_genctrl_active;
				if (gen316_cyclix_var) {
					genpstage_EXEC_genctrl_stalled_glbl = ap_uint<32>(1);
				}
				genpstage_EXEC_genctrl_active = ap_uint<32>(0);
			}
		}
		gen282_pipex_var = genpstage_EXEC_TRX_LOCAL.mem_req;
		gen317_cyclix_var = gen282_pipex_var;
		if (gen317_cyclix_var) {
			gen283_pipex_var = ~genpstage_EXEC_TRX_LOCAL.mem_cmd;
			gen284_pipex_var = gen283_pipex_var;
			gen318_cyclix_var = gen284_pipex_var;
			if (gen318_cyclix_var) {
				gen319_cyclix_var = genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_data_mem.resp_done;
				if (gen319_cyclix_var) {
					genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_data_mem.rdata;
				}
				gen285_pipex_var = genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_data_mem.resp_done;
				gen286_pipex_var = gen285_pipex_var;
				gen320_cyclix_var = gen286_pipex_var;
				if (gen320_cyclix_var) {
					genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
				}
				gen287_pipex_var = ap_uint<1>(0);
				gen287_pipex_var = (gen287_pipex_var || gen286_pipex_var);
				gen287_pipex_var = !gen287_pipex_var;
				gen321_cyclix_var = gen287_pipex_var;
				if (gen321_cyclix_var) {
					gen322_cyclix_var = genpstage_EXEC_genctrl_active;
					if (gen322_cyclix_var) {
						genpstage_EXEC_genctrl_stalled_glbl = ap_uint<32>(1);
					}
					genpstage_EXEC_genctrl_active = ap_uint<32>(0);
				}
			}
		}
		gen288_pipex_var = (genpstage_EXEC_TRX_LOCAL.mem_be == ap_uint<32>(1));
		gen289_pipex_var = gen288_pipex_var;
		gen323_cyclix_var = gen289_pipex_var;
		if (gen323_cyclix_var) {
			gen290_pipex_var = genpstage_EXEC_TRX_LOCAL.load_signext;
			gen324_cyclix_var = gen290_pipex_var;
			if (gen324_cyclix_var) {
				gen291_pipex_var = genpstage_EXEC_TRX_LOCAL.mem_rdata[7:0];
				gen292_pipex_var = gen291_pipex_var[7];
				gen293_pipex_var = gen292_pipex_var.concat((ap_uint<31>)gen292_pipex_var.concat((ap_uint<30>)gen292_pipex_var.concat((ap_uint<29>)gen292_pipex_var.concat((ap_uint<28>)gen292_pipex_var.concat((ap_uint<27>)gen292_pipex_var.concat((ap_uint<26>)gen292_pipex_var.concat((ap_uint<25>)gen292_pipex_var.concat((ap_uint<24>)gen292_pipex_var.concat((ap_uint<23>)gen292_pipex_var.concat((ap_uint<22>)gen292_pipex_var.concat((ap_uint<21>)gen292_pipex_var.concat((ap_uint<20>)gen292_pipex_var.concat((ap_uint<19>)gen292_pipex_var.concat((ap_uint<18>)gen292_pipex_var.concat((ap_uint<17>)gen292_pipex_var.concat((ap_uint<16>)gen292_pipex_var.concat((ap_uint<15>)gen292_pipex_var.concat((ap_uint<14>)gen292_pipex_var.concat((ap_uint<13>)gen292_pipex_var.concat((ap_uint<12>)gen292_pipex_var.concat((ap_uint<11>)gen292_pipex_var.concat((ap_uint<10>)gen292_pipex_var.concat((ap_uint<9>)gen292_pipex_var.concat((ap_uint<8>)genpstage_EXEC_TRX_LOCAL.mem_rdata[7:0]))))))))))))))))))))))));
				genpstage_EXEC_TRX_LOCAL = gen293_pipex_var;
			}
			gen294_pipex_var = ap_uint<1>(0);
			gen294_pipex_var = (gen294_pipex_var || gen290_pipex_var);
			gen294_pipex_var = !gen294_pipex_var;
			gen325_cyclix_var = gen294_pipex_var;
			if (gen325_cyclix_var) {
				gen295_pipex_var = ap_uint<24>(0).concat((ap_uint<8>)genpstage_EXEC_TRX_LOCAL.mem_rdata[7:0]);
				genpstage_EXEC_TRX_LOCAL = gen295_pipex_var;
			}
		}
		gen296_pipex_var = (genpstage_EXEC_TRX_LOCAL.mem_be == ap_uint<32>(3));
		gen297_pipex_var = gen296_pipex_var;
		gen326_cyclix_var = gen297_pipex_var;
		if (gen326_cyclix_var) {
			gen298_pipex_var = genpstage_EXEC_TRX_LOCAL.load_signext;
			gen327_cyclix_var = gen298_pipex_var;
			if (gen327_cyclix_var) {
				gen299_pipex_var = genpstage_EXEC_TRX_LOCAL.mem_rdata[15:0];
				gen300_pipex_var = gen299_pipex_var[15];
				gen301_pipex_var = gen300_pipex_var.concat((ap_uint<31>)gen300_pipex_var.concat((ap_uint<30>)gen300_pipex_var.concat((ap_uint<29>)gen300_pipex_var.concat((ap_uint<28>)gen300_pipex_var.concat((ap_uint<27>)gen300_pipex_var.concat((ap_uint<26>)gen300_pipex_var.concat((ap_uint<25>)gen300_pipex_var.concat((ap_uint<24>)gen300_pipex_var.concat((ap_uint<23>)gen300_pipex_var.concat((ap_uint<22>)gen300_pipex_var.concat((ap_uint<21>)gen300_pipex_var.concat((ap_uint<20>)gen300_pipex_var.concat((ap_uint<19>)gen300_pipex_var.concat((ap_uint<18>)gen300_pipex_var.concat((ap_uint<17>)gen300_pipex_var.concat((ap_uint<16>)genpstage_EXEC_TRX_LOCAL.mem_rdata[15:0]))))))))))))))));
				genpstage_EXEC_TRX_LOCAL = gen301_pipex_var;
			}
			gen302_pipex_var = ap_uint<1>(0);
			gen302_pipex_var = (gen302_pipex_var || gen298_pipex_var);
			gen302_pipex_var = !gen302_pipex_var;
			gen328_cyclix_var = gen302_pipex_var;
			if (gen328_cyclix_var) {
				gen303_pipex_var = ap_uint<16>(0).concat((ap_uint<16>)genpstage_EXEC_TRX_LOCAL.mem_rdata[15:0]);
				genpstage_EXEC_TRX_LOCAL = gen303_pipex_var;
			}
		}
		gen304_pipex_var = (genpstage_EXEC_TRX_LOCAL.rd_source == ap_uint<32>(5));
		gen305_pipex_var = gen304_pipex_var;
		gen329_cyclix_var = gen305_pipex_var;
		if (gen329_cyclix_var) {
			genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_LOCAL.mem_rdata;
		}
		gen306_pipex_var = genpstage_EXEC_TRX_LOCAL.ext_coproc_req;
		gen330_cyclix_var = gen306_pipex_var;
		if (gen330_cyclix_var) {
			gen331_cyclix_var = genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_coproc_M_if.resp_done;
			if (gen331_cyclix_var) {
				genpstage_EXEC_TRX_LOCAL = genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_coproc_M_if.rdata;
			}
			gen307_pipex_var = genpstage_EXEC_TRX_BUF[0].genmcopipe_handle_coproc_M_if.resp_done;
			gen308_pipex_var = gen307_pipex_var;
			gen332_cyclix_var = gen308_pipex_var;
			if (gen332_cyclix_var) {
				genpstage_EXEC_TRX_LOCAL = ap_uint<32>(1);
			}
			gen309_pipex_var = ap_uint<1>(0);
			gen309_pipex_var = (gen309_pipex_var || gen308_pipex_var);
			gen309_pipex_var = !gen309_pipex_var;
			gen333_cyclix_var = gen309_pipex_var;
			if (gen333_cyclix_var) {
				gen334_cyclix_var = genpstage_EXEC_genctrl_active;
				if (gen334_cyclix_var) {
					genpstage_EXEC_genctrl_stalled_glbl = ap_uint<32>(1);
				}
				genpstage_EXEC_genctrl_active = ap_uint<32>(0);
			}
		}
		gen310_pipex_var = (genpstage_EXEC_TRX_LOCAL.rd_req && genpstage_EXEC_TRX_LOCAL.rd_rdy);
		gen311_pipex_var = gen310_pipex_var;
		gen335_cyclix_var = gen311_pipex_var;
		if (gen335_cyclix_var) {
			genpsticky_glbl_regfile = genpstage_EXEC_TRX_LOCAL.rd_wdata;
		}
		// Processing of next pstage busyness
		// pctrl_finish and pctrl_succ formation
		gen336_cyclix_var = genpstage_EXEC_genctrl_stalled_glbl;
		if (gen336_cyclix_var) {
			genpstage_EXEC_genctrl_finish = ap_uint<32>(0);
			genpstage_EXEC_genctrl_succ = ap_uint<32>(0);
		}
		gen337_cyclix_var = ap_uint<1>(0);
		gen337_cyclix_var = (gen337_cyclix_var || gen336_cyclix_var);
		gen337_cyclix_var = !gen337_cyclix_var;
		if (gen337_cyclix_var) {
			genpstage_EXEC_genctrl_finish = genpstage_EXEC_genctrl_occupied;
			genpstage_EXEC_genctrl_succ = genpstage_EXEC_genctrl_active;
		}
		// credit counter processing
		// asserting succ signals
		// processing context in case transaction is ready to propagate
		gen338_cyclix_var = genpstage_EXEC_genctrl_finish;
		if (gen338_cyclix_var) {
			// programming next stage in case transaction is able to propagate
			gen339_cyclix_var = genpstage_EXEC_genctrl_succ;
			if (gen339_cyclix_var) {
			}
			genpstage_EXEC_genctrl_stalled_glbl = ap_uint<32>(0);
			genpstage_EXEC_TRX_BUF = '{default:ap_uint<32>(0)};
			genpstage_EXEC_TRX_BUF_COUNTER_FULL = ap_uint<32>(0);
			genpstage_EXEC_TRX_BUF_COUNTER_NEMPTY = ap_uint<32>(0);
			genpstage_EXEC_TRX_BUF_COUNTER = (genpstage_EXEC_TRX_BUF_COUNTER - ap_uint<32>(1));
		}
		gen340_cyclix_var = ~genpstage_EXEC_TRX_BUF_COUNTER_FULL;
		genpstage_EXEC_genctrl_rdy = gen340_cyclix_var;
		genpstage_EXEC_genctrl_working = (genpstage_EXEC_genctrl_succ | genpstage_EXEC_genctrl_stalled_glbl);
		// #### Stage processing: IFETCH ####
		genpstage_IFETCH_genctrl_succ = ap_uint<32>(0);
		genpstage_IFETCH_genctrl_working = ap_uint<32>(0);
		gen341_cyclix_var = genpstage_IFETCH_genctrl_stalled_glbl;
		if (gen341_cyclix_var) {
			genpstage_IFETCH_genctrl_new = ap_uint<32>(0);
			genpstage_IFETCH_genctrl_stalled_glbl = ap_uint<32>(0);
			genpstage_IFETCH_genctrl_active = ap_uint<32>(1);
		}
		gen342_cyclix_var = ap_uint<1>(0);
		gen342_cyclix_var = (gen342_cyclix_var || gen341_cyclix_var);
		gen342_cyclix_var = !gen342_cyclix_var;
		if (gen342_cyclix_var) {
			genpstage_IFETCH_genctrl_active = ap_uint<32>(1);
			genpstage_IFETCH_genctrl_new = genpstage_IFETCH_genctrl_active;
		}
		genpstage_IFETCH_genctrl_occupied = genpstage_IFETCH_genctrl_active;
		genpstage_IFETCH_genctrl_finish = ap_uint<32>(0);
		genpstage_IFETCH_genpctrl_flushreq = ap_uint<32>(0);
		genpstage_IFETCH_genpctrl_flushreq = (genpstage_IFETCH_genpctrl_flushreq | genpstage_EXEC_genpctrl_flushreq);
		gen343_cyclix_var = genpstage_IFETCH_genctrl_occupied;
		if (gen343_cyclix_var) {
			// Initializing new newaccums descriptors ####
			gen344_cyclix_var = genpstage_IFETCH_genctrl_new;
			if (gen344_cyclix_var) {
				genpstage_IFETCH_TRX_BUF = ap_uint<32>(0);
			}
			// Fetching locals from src_glbls
			genpstage_IFETCH_TRX_LOCAL = ap_uint<32>(0);
			genpstage_IFETCH_TRX_LOCAL = ap_uint<32>(0);
			genpstage_IFETCH_TRX_LOCAL = genpstage_IFETCH_TRX_BUF[0].instr_req_done;
			genpstage_IFETCH_TRX_LOCAL = '{default:ap_uint<32>(0)};
			// Acquiring mcopipe rdata
			gen345_cyclix_var = genpstage_IFETCH_TRX_BUF[0].genmcopipe_handle_instr_mem.rdreq_pending;
			if (gen345_cyclix_var) {
				gen346_cyclix_var = (genpstage_IFETCH_TRX_BUF[0].genmcopipe_handle_instr_mem.if_id == ap_uint<1>(0));
				gen347_cyclix_var = gen346_cyclix_var;
				if (gen347_cyclix_var) {
					gen348_cyclix_var = (genpstage_IFETCH_TRX_BUF[0].genmcopipe_handle_instr_mem.tid == genmcopipe_instr_mem_rd_ptr);
					gen349_cyclix_var = gen348_cyclix_var;
					if (gen349_cyclix_var) {
						gen350_cyclix_var = genmcopipe_instr_mem_resp.read_nb(gen319_pipex_mcopipe_rdata);
						gen351_cyclix_var = gen350_cyclix_var;
						if (gen351_cyclix_var) {
							genpstage_IFETCH_TRX_BUF = ap_uint<32>(0);
							genpstage_IFETCH_TRX_BUF = ap_uint<32>(1);
							genpstage_IFETCH_TRX_BUF = gen319_pipex_mcopipe_rdata;
							genmcopipe_instr_mem_rd_done = ap_uint<32>(1);
						}
					}
				}
			}
			// Pipeline flush processing
			gen352_cyclix_var = genpstage_IFETCH_genpctrl_flushreq;
			if (gen352_cyclix_var) {
			}
		}
		// Saving succ targets
		gen156_pipex_succbuf = genpsticky_glbl_pc;
		// Generating payload
		gen157_pipex_var = genpsticky_glbl_jump_req_cmd;
		gen353_cyclix_var = gen157_pipex_var;
		if (gen353_cyclix_var) {
			gen354_cyclix_var = genpstage_IFETCH_genctrl_active;
			if (gen354_cyclix_var) {
				genpsticky_glbl_pc = genpsticky_glbl_jump_vector_cmd;
			}
			gen355_cyclix_var = genpstage_IFETCH_genctrl_active;
			if (gen355_cyclix_var) {
				genpsticky_glbl_jump_req_cmd = ap_uint<32>(0);
			}
		}
		genpstage_IFETCH_TRX_LOCAL = genpsticky_glbl_pc;
		gen158_pipex_var = (genpstage_IFETCH_TRX_LOCAL.curinstr_addr + ap_uint<32>(4));
		genpstage_IFETCH_TRX_LOCAL = gen158_pipex_var;
		gen155_pipex_succreq = ap_uint<32>(1);
		gen156_pipex_succbuf = genpstage_IFETCH_TRX_LOCAL.nextinstr_addr;
		gen159_pipex_var = genpsticky_glbl_jump_req_cmd;
		gen356_cyclix_var = gen159_pipex_var;
		if (gen356_cyclix_var) {
			genpstage_IFETCH_TRX_LOCAL = ap_uint<32>(0);
			gen357_cyclix_var = genpstage_IFETCH_genctrl_active;
			if (gen357_cyclix_var) {
				genpstage_IFETCH_TRX_BUF = ap_uint<32>(0);
			}
		}
		genpstage_IFETCH_TRX_LOCAL = genpstage_IFETCH_TRX_LOCAL.curinstr_addr;
		genpstage_IFETCH_TRX_LOCAL = ap_uint<32>(15);
		genpstage_IFETCH_TRX_LOCAL = ap_uint<32>(0);
		gen160_pipex_var = ~genpstage_IFETCH_TRX_LOCAL.instr_req_done;
		gen161_pipex_var = gen160_pipex_var;
		gen358_cyclix_var = gen161_pipex_var;
		if (gen358_cyclix_var) {
			gen359_cyclix_var = genpstage_IFETCH_genctrl_active;
			if (gen359_cyclix_var) {
				gen360_cyclix_var = ~genmcopipe_instr_mem_full_flag;
				gen361_cyclix_var = gen360_cyclix_var;
				if (gen361_cyclix_var) {
					gen320_pipex_req_struct = ap_uint<1>(0);
					gen320_pipex_req_struct = genpstage_IFETCH_TRX_LOCAL.instr_busreq;
					gen362_cyclix_var = genmcopipe_instr_mem_req.write_nb(gen320_pipex_req_struct);
					gen363_cyclix_var = gen362_cyclix_var;
					if (gen363_cyclix_var) {
						gen162_pipex_var = ap_uint<32>(1);
						gen364_cyclix_var = !ap_uint<1>(0);
						genpstage_IFETCH_TRX_BUF = gen364_cyclix_var;
						genpstage_IFETCH_TRX_BUF = genmcopipe_instr_mem_wr_ptr;
						genpstage_IFETCH_TRX_BUF = ap_uint<1>(0);
						gen365_cyclix_var = genpstage_IFETCH_TRX_BUF[0].genmcopipe_handle_instr_mem.rdreq_pending;
						if (gen365_cyclix_var) {
							genmcopipe_instr_mem_wr_done = ap_uint<32>(1);
						}
					}
				}
			}
			genpstage_IFETCH_TRX_LOCAL = gen162_pipex_var;
			gen366_cyclix_var = genpstage_IFETCH_genctrl_active;
			if (gen366_cyclix_var) {
				genpstage_IFETCH_TRX_BUF = gen162_pipex_var;
			}
		}
		gen163_pipex_var = ~genpstage_IFETCH_TRX_LOCAL.instr_req_done;
		gen164_pipex_var = gen163_pipex_var;
		gen367_cyclix_var = gen164_pipex_var;
		if (gen367_cyclix_var) {
			gen368_cyclix_var = genpstage_IFETCH_genctrl_active;
			if (gen368_cyclix_var) {
				genpstage_IFETCH_genctrl_stalled_glbl = ap_uint<32>(1);
			}
			genpstage_IFETCH_genctrl_active = ap_uint<32>(0);
		}
		// Processing of next pstage busyness
		gen369_cyclix_var = ~genpstage_EXEC_genctrl_rdy;
		gen370_cyclix_var = gen369_cyclix_var;
		if (gen370_cyclix_var) {
			gen371_cyclix_var = genpstage_IFETCH_genctrl_active;
			if (gen371_cyclix_var) {
				genpstage_IFETCH_genctrl_stalled_glbl = ap_uint<32>(1);
			}
			genpstage_IFETCH_genctrl_active = ap_uint<32>(0);
		}
		// pctrl_finish and pctrl_succ formation
		gen372_cyclix_var = genpstage_IFETCH_genctrl_stalled_glbl;
		if (gen372_cyclix_var) {
			genpstage_IFETCH_genctrl_finish = ap_uint<32>(0);
			genpstage_IFETCH_genctrl_succ = ap_uint<32>(0);
		}
		gen373_cyclix_var = ap_uint<1>(0);
		gen373_cyclix_var = (gen373_cyclix_var || gen372_cyclix_var);
		gen373_cyclix_var = !gen373_cyclix_var;
		if (gen373_cyclix_var) {
			genpstage_IFETCH_genctrl_finish = genpstage_IFETCH_genctrl_occupied;
			genpstage_IFETCH_genctrl_succ = genpstage_IFETCH_genctrl_active;
		}
		// credit counter processing
		// asserting succ signals
		gen374_cyclix_var = genpstage_IFETCH_genctrl_succ;
		if (gen374_cyclix_var) {
			gen375_cyclix_var = gen155_pipex_succreq;
			if (gen375_cyclix_var) {
				genpsticky_glbl_pc = gen156_pipex_succbuf;
			}
		}
		// processing context in case transaction is ready to propagate
		gen376_cyclix_var = genpstage_IFETCH_genctrl_finish;
		if (gen376_cyclix_var) {
			// programming next stage in case transaction is able to propagate
			gen377_cyclix_var = genpstage_IFETCH_genctrl_succ;
			if (gen377_cyclix_var) {
				gen378_cyclix_var = genpstage_EXEC_genctrl_rdy;
				if (gen378_cyclix_var) {
					// propagating transaction context
					genpstage_EXEC_push_trx = genpstage_IFETCH_TRX_LOCAL.curinstr_addr;
					genpstage_EXEC_push_trx = genpstage_IFETCH_TRX_LOCAL.nextinstr_addr;
					genpstage_EXEC_push_trx = genpstage_IFETCH_TRX_BUF[0].genmcopipe_handle_instr_mem.if_id;
					genpstage_EXEC_push_trx = genpstage_IFETCH_TRX_BUF[0].genmcopipe_handle_instr_mem.resp_done;
					genpstage_EXEC_push_trx = genpstage_IFETCH_TRX_BUF[0].genmcopipe_handle_instr_mem.rdata;
					genpstage_EXEC_push_trx = genpstage_IFETCH_TRX_BUF[0].genmcopipe_handle_instr_mem.rdreq_pending;
					genpstage_EXEC_push_trx = genpstage_IFETCH_TRX_BUF[0].genmcopipe_handle_instr_mem.tid;
					genpstage_EXEC_TRX_PUSHED = genpstage_EXEC_push_trx;
					genpstage_EXEC_TRX_BUF = genpstage_EXEC_push_trx;
					genpstage_EXEC_TRX_BUF_COUNTER_NEMPTY = ap_uint<32>(1);
					genpstage_EXEC_TRX_BUF_COUNTER_FULL = ap_uint<32>(1);
					genpstage_EXEC_TRX_BUF_COUNTER = (genpstage_EXEC_TRX_BUF_COUNTER + ap_uint<32>(1));
				}
			}
			genpstage_IFETCH_genctrl_stalled_glbl = ap_uint<32>(0);
			genpstage_IFETCH_TRX_BUF = '{default:ap_uint<32>(0)};
			genpstage_IFETCH_TRX_BUF_COUNTER_FULL = ap_uint<32>(0);
			genpstage_IFETCH_TRX_BUF_COUNTER_NEMPTY = ap_uint<32>(0);
			genpstage_IFETCH_TRX_BUF_COUNTER = (genpstage_IFETCH_TRX_BUF_COUNTER - ap_uint<32>(1));
		}
		gen379_cyclix_var = ~genpstage_IFETCH_TRX_BUF_COUNTER_FULL;
		genpstage_IFETCH_genctrl_rdy = gen379_cyclix_var;
		genpstage_IFETCH_genctrl_working = (genpstage_IFETCH_genctrl_succ | genpstage_IFETCH_genctrl_stalled_glbl);
		gen380_cyclix_var = genmcopipe_instr_mem_rd_done;
		if (gen380_cyclix_var) {
			genmcopipe_instr_mem_rd_ptr = genmcopipe_instr_mem_rd_ptr_next;
			genmcopipe_instr_mem_full_flag = ap_uint<32>(0);
			gen381_cyclix_var = (genmcopipe_instr_mem_rd_ptr == genmcopipe_instr_mem_wr_ptr);
			gen382_cyclix_var = gen381_cyclix_var;
			if (gen382_cyclix_var) {
				genmcopipe_instr_mem_empty_flag = ap_uint<32>(1);
			}
		}
		gen383_cyclix_var = genmcopipe_instr_mem_wr_done;
		if (gen383_cyclix_var) {
			genmcopipe_instr_mem_wr_ptr = genmcopipe_instr_mem_wr_ptr_next;
			genmcopipe_instr_mem_empty_flag = ap_uint<32>(0);
			gen384_cyclix_var = (genmcopipe_instr_mem_rd_ptr == genmcopipe_instr_mem_wr_ptr);
			gen385_cyclix_var = gen384_cyclix_var;
			if (gen385_cyclix_var) {
				genmcopipe_instr_mem_full_flag = ap_uint<32>(1);
			}
		}
		gen386_cyclix_var = genmcopipe_data_mem_rd_done;
		if (gen386_cyclix_var) {
			genmcopipe_data_mem_rd_ptr = genmcopipe_data_mem_rd_ptr_next;
			genmcopipe_data_mem_full_flag = ap_uint<32>(0);
			gen387_cyclix_var = (genmcopipe_data_mem_rd_ptr == genmcopipe_data_mem_wr_ptr);
			gen388_cyclix_var = gen387_cyclix_var;
			if (gen388_cyclix_var) {
				genmcopipe_data_mem_empty_flag = ap_uint<32>(1);
			}
		}
		gen389_cyclix_var = genmcopipe_data_mem_wr_done;
		if (gen389_cyclix_var) {
			genmcopipe_data_mem_wr_ptr = genmcopipe_data_mem_wr_ptr_next;
			genmcopipe_data_mem_empty_flag = ap_uint<32>(0);
			gen390_cyclix_var = (genmcopipe_data_mem_rd_ptr == genmcopipe_data_mem_wr_ptr);
			gen391_cyclix_var = gen390_cyclix_var;
			if (gen391_cyclix_var) {
				genmcopipe_data_mem_full_flag = ap_uint<32>(1);
			}
		}
		gen392_cyclix_var = genmcopipe_coproc_M_if_rd_done;
		if (gen392_cyclix_var) {
			genmcopipe_coproc_M_if_rd_ptr = genmcopipe_coproc_M_if_rd_ptr_next;
			genmcopipe_coproc_M_if_full_flag = ap_uint<32>(0);
			gen393_cyclix_var = (genmcopipe_coproc_M_if_rd_ptr == genmcopipe_coproc_M_if_wr_ptr);
			gen394_cyclix_var = gen393_cyclix_var;
			if (gen394_cyclix_var) {
				genmcopipe_coproc_M_if_empty_flag = ap_uint<32>(1);
			}
		}
		gen395_cyclix_var = genmcopipe_coproc_M_if_wr_done;
		if (gen395_cyclix_var) {
			genmcopipe_coproc_M_if_wr_ptr = genmcopipe_coproc_M_if_wr_ptr_next;
			genmcopipe_coproc_M_if_empty_flag = ap_uint<32>(0);
			gen396_cyclix_var = (genmcopipe_coproc_M_if_rd_ptr == genmcopipe_coproc_M_if_wr_ptr);
			gen397_cyclix_var = gen396_cyclix_var;
			if (gen397_cyclix_var) {
				genmcopipe_coproc_M_if_full_flag = ap_uint<32>(1);
			}
		}
		gen398_cyclix_var = genmcopipe_coproc_custom0_if_rd_done;
		if (gen398_cyclix_var) {
			genmcopipe_coproc_custom0_if_rd_ptr = genmcopipe_coproc_custom0_if_rd_ptr_next;
			genmcopipe_coproc_custom0_if_full_flag = ap_uint<32>(0);
			gen399_cyclix_var = (genmcopipe_coproc_custom0_if_rd_ptr == genmcopipe_coproc_custom0_if_wr_ptr);
			gen400_cyclix_var = gen399_cyclix_var;
			if (gen400_cyclix_var) {
				genmcopipe_coproc_custom0_if_empty_flag = ap_uint<32>(1);
			}
		}
		gen401_cyclix_var = genmcopipe_coproc_custom0_if_wr_done;
		if (gen401_cyclix_var) {
			genmcopipe_coproc_custom0_if_wr_ptr = genmcopipe_coproc_custom0_if_wr_ptr_next;
			genmcopipe_coproc_custom0_if_empty_flag = ap_uint<32>(0);
			gen402_cyclix_var = (genmcopipe_coproc_custom0_if_rd_ptr == genmcopipe_coproc_custom0_if_wr_ptr);
			gen403_cyclix_var = gen402_cyclix_var;
			if (gen403_cyclix_var) {
				genmcopipe_coproc_custom0_if_full_flag = ap_uint<32>(1);
			}
		}
	}
}
